### ISSUE TITLE
Can't select obstacle for seismic charge

### ISSUE THREAD

**Issue by Croste** [Sandrem/FlyCasual#1681] opened 2019-03-19 05:46 UTC
Again me, on my S6. Can't select obstacle to be destroyed with seismic charge. Used touch and stylist.

**Comment by Sandrem** [comment] 2019-03-22 23:27
Duplicate of https://github.com/Sandrem/FlyCasual/issues/1526
Closed.

**Closed by Sandrem** 2019-03-22 23:27 UTC
