### ISSUE TITLE
Dash Rendar's ability does not work

### ISSUE THREAD

**Issue by Tech55b** [Sandrem/FlyCasual#406] opened 2017-12-15 01:29 UTC
You still lose the ability to take actions if you land on an asteroid in the activation phase

**Comment by Sandrem** [comment] 2017-12-15 21:08
I cannot reproduce this problem.
Can you provide a screenshot, where error "Cannot take actions" is shown for Dash Rendar?

**Comment by Tech55b** [comment] 2017-12-16 03:06
I tested this myself again over about 10 games I only got it to happen again once, but I wasn’t able to get a screenshot in time to get the notification.

While I was testing it however I had another issue come up where using R5-K6 with Nora Wexley cause the debugger to show up and the game to stop. I have included a screenshot for you.

Regards

Anthony

P.S I’m loving what your doing with the game, keep it up!

________________________________

**Comment by Sandrem** [comment] 2017-12-16 03:52
At the moment I have only 1 report about this. I will close this issue, try to encounter same bug with Dash Rendar in 0.3.2 with steps to reproduce or screenshot at least. 

R5-K6 had bug, I already fixed it, will be in 0.3.2 soon.

Thanks for help =)

**Closed by Sandrem** 2017-12-16 03:52 UTC
Labels: Bug, Cannot reproduce
