### ISSUE TITLE
Null pointer at assign tractor

### ISSUE THREAD

**Issue by otuv** [Sandrem/FlyCasual#2886] opened 2020-08-26 18:11 UTC
![Screenshot from 2020-08-26 20-08-42](https://user-images.githubusercontent.com/16488095/91340260-fef9f380-e7d7-11ea-9551-2c11b9f41a1c.png)

Black Squadron Ace has just been assigned a tractor token from Thanisson.

[LastReplay.replay.zip](https://github.com/Sandrem/FlyCasual/files/5131539/LastReplay.replay.zip)

**Comment by rune-b** [comment] 2020-08-26 19:35
Duplicate of #2883

**Closed by rune-b** 2020-08-26 19:35 UTC
