### ISSUE TITLE
Zeb Orrelios crew not working on Han Solo

### ISSUE THREAD

**Issue by Karl4242** [Sandrem/FlyCasual#3245] opened 2021-04-15 19:04 UTC
Zeb crew on Han.  Still says, "not a valid target" when Han tries to shoot a range0 opponent in side arc.  possibly front/rear

**Comment by Karl4242** [comment] 2021-04-19 15:49
now trying zeb on Hera (VCX) same issue.

**Comment by Sandrem** [comment] 2021-05-08 14:01
Duplicate of https://github.com/Sandrem/FlyCasual/issues/3109

**Closed by Sandrem** 2021-05-08 14:01 UTC
