### ISSUE TITLE
Cards and Avatars don't load on linux

### ISSUE THREAD

**Issue by leoarthur83** [Sandrem/FlyCasual#2347] opened 2019-10-24 10:12 UTC
Hi, friends.
I'm runing Fly Casual in OpenSUSE Tumbleweed. Cards and Avatars images don't load. There is a active internet connection. There is a way to verify the problem?
Your simulator is incredible! Thanks for the amazing work!

![Screenshot from 2019-10-24 07-11-06](https://user-images.githubusercontent.com/36453423/67476012-9aa55b00-f62d-11e9-8e7a-1b3f0a4c8edc.png)

**Comment by rune-b** [comment] 2019-10-24 15:42
Hi
The card and avatar images are not included in the game, but downloaded from the internet when the game starts. Are you sure there is no problem with your connection? Or a firewall or something?

**Comment by rune-b** [comment] 2019-10-24 15:45
Can you try accessing this image directly from your web browser and see if it works there?

https://sb-cdn.fantasyflightgames.com/card_images/en/d60f4eca355471465ca3f6b99fb98e56.png

**Comment by nix-7** [comment] 2019-10-26 14:50
I experience the exact same issue on Fedora 30
Absolutely no network connection, nor firewall issue.
snip of ~/.config/unity3d/Editor/Player.log

```Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Upgrade_109.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)

Unloading 83 unused Assets to reduce memory usage. Loaded Objects now: 4224.
Total: 12.224027 ms (FindLiveObjects: 0.358572 ms CreateObjectMapping: 0.076864 ms MarkObjects: 11.654219 ms  DeleteObjects: 0.133651 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 14 unused Assets to reduce memory usage. Loaded Objects now: 4299.
Total: 11.762842 ms (FindLiveObjects: 0.394290 ms CreateObjectMapping: 0.046918 ms MarkObjects: 11.288883 ms  DeleteObjects: 0.032370 ms)

Cannot download image: https://images-cdn.fantasyflightgames.com/filer_public/f9/24/f9246e39-4852-4a8f-a331-9b78f62439e9/swz32_obi-wan-kenobi.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://images-cdn.fantasyflightgames.com/filer_public/ff/29/ff29970e-5ed7-416d-b5da-3918e226b3dc/swz33_odd-ball.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://images-cdn.fantasyflightgames.com/filer_public/6c/73/6c73ec27-bf29-4ace-86e9-4d03cdafa884/swz48_pilot-shadow-vet.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://images-cdn.fantasyflightgames.com/filer_public/d2/7b/d27baa36-e835-4311-b86b-b9b19ce8a0b9/swz40_ric-olie.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://images-cdn.fantasyflightgames.com/filer_public/57/c4/57c43689-5d1f-4fd2-b1f6-d4bec9448634/swz32_kickback.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 41 unused Assets to reduce memory usage. Loaded Objects now: 4691.
Total: 14.493434 ms (FindLiveObjects: 0.343084 ms CreateObjectMapping: 0.043031 ms MarkObjects: 14.060882 ms  DeleteObjects: 0.046107 ms)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/en/d60f4eca355471465ca3f6b99fb98e56.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://images-cdn.fantasyflightgames.com/filer_public/77/73/777350cb-614b-48fd-ad8d-d9c867053c6b/swz32_saesee-tiin.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/en/7f87b6c12631687bedf75a18582af0b0.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://images-cdn.fantasyflightgames.com/filer_public/f9/24/f9246e39-4852-4a8f-a331-9b78f62439e9/swz32_obi-wan-kenobi.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/en/15f6bf84f63970c982dd722a5473217f.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://images-cdn.fantasyflightgames.com/filer_public/6a/6f/6a6fef51-fb5f-49c1-b5cc-8e96b6d09051/swz32_plo-koon.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://images-cdn.fantasyflightgames.com/filer_public/de/33/de3326f7-521c-4f50-8599-483db5f32d6d/swz32_mace-windu.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/en/f8f58005da18d7041b1ec2374701465c.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://images-cdn.fantasyflightgames.com/filer_public/b0/b3/b0b3f463-a3ea-4fe6-be69-41afed1b4110/swz32_jedi-knight.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 62 unused Assets to reduce memory usage. Loaded Objects now: 4736.
Total: 13.611078 ms (FindLiveObjects: 0.386224 ms CreateObjectMapping: 0.060674 ms MarkObjects: 13.105080 ms  DeleteObjects: 0.058730 ms)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/en/d60f4eca355471465ca3f6b99fb98e56.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Upgrade_109.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

```
curl to show no issues access URLs
```$ curl -v https://images-cdn.fantasyflightgames.com/filer_public/f9/24/f9246e39-4852-4a8f-a331-9b78f62439e9/swz32_obi-wan-kenobi.png
*   Trying 104.20.244.8:443...
* TCP_NODELAY set
* Connected to images-cdn.fantasyflightgames.com (104.20.244.8) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; OU=PositiveSSL Multi-Domain; CN=ssl512425.cloudflaressl.com
*  start date: Aug 24 00:00:00 2019 GMT
*  expire date: Mar  1 23:59:59 2020 GMT
*  subjectAltName: host "images-cdn.fantasyflightgames.com" matched cert's "*.fantasyflightgames.com"
*  issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO ECC Domain Validation Secure Server CA 2
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x561f7ce6ba40)
> GET /filer_public/f9/24/f9246e39-4852-4a8f-a331-9b78f62439e9/swz32_obi-wan-kenobi.png HTTP/2
> Host: images-cdn.fantasyflightgames.com
> User-Agent: curl/7.65.3
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200 
< date: Sat, 26 Oct 2019 14:49:00 GMT
< content-type: image/png
< content-length: 191968
< set-cookie: __cfduid=d513458ab9db847b14e04a6745adafb301572101339; expires=Sun, 25-Oct-20 14:48:59 GMT; path=/; domain=.fantasyflightgames.com; HttpOnly
< x-amz-replication-status: COMPLETED
< last-modified: Tue, 18 Dec 2018 22:35:47 GMT
< etag: "21f925a047dca22c30765490656ba7cd"
< x-amz-version-id: XAiCH2P1aafBK_wLl6ehcw0.lzeDPfgg
< x-cache: Miss from cloudfront
< via: 1.1 44a651f8e3a1f38a5a977c4f0c4d45a0.cloudfront.net (CloudFront)
< x-amz-cf-pop: LHR52-C1
< x-amz-cf-id: U0AWVCPqJQXXTUrF9Q5X_UoMo3Mth8TvX7gXc6DhYz8_UNCcMr0rKQ==
< cf-cache-status: MISS
< accept-ranges: bytes
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 52bd3bfdef58d224-MAN
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 810)
* stopped the pause stream!
* Connection #0 to host images-cdn.fantasyflightgames.com left intact
```

**Comment by rune-b** [comment] 2019-10-26 14:55
Could the problem be the writing to disk, and not the network? Perhaps it is a rights issue. Not sure which folder it tries to write them to on Linux...

**Comment by nix-7** [comment] 2019-10-26 15:16
Well monitoring the network, it makes successful TCP connection on port 443 (to images-cdn.fantasyflightgames.com), then immediately closes the connection with a FIN packet, every single connection attempt. It never attempts the HTTPS handshake. So it's not a disk writing issue as it doesn't get a single bit downloaded. ext4 permissions are all set in the entire directory structure to allow writing for user account anyway.


![fc_tcp1](https://user-images.githubusercontent.com/57040380/67621872-f9283000-f80b-11e9-8d5a-e2a70e4dc145.jpg)

**Comment by rune-b** [comment] 2019-10-26 16:07
Has it worked for you before? If so, do you know when it stopped working?

**Comment by nix-7** [comment] 2019-10-26 16:10
> Has it worked for you before? If so, do you know when it stopped working?

Sadly not, only ever used v0.9.6

**Comment by rune-b** [comment] 2019-11-05 20:23
I will try adding some more logging of error messages when downloading images, so hopefully that will give us more to work with here.

**Comment by rune-b** [comment] 2020-01-27 19:18
@nix-7 @leoarthur83 Have you tried the latest release? I have added some more details to the logging, so now the player.log will hopefully contain more useful info about the cause of this problem

**Comment by nix-7** [comment] 2020-01-28 09:17
Sadly the exact same results with v0.9.7.1. The ~/.config/unity3d/Editor/Player.log doesn't appear to show anything  useful other than it failed. Which I've shown, there is zero connectivity issue, nor firewall blocking.

`Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Upgrade_109.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Upgrade_109.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Upgrade_109.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Upgrade_109.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)

Unloading 155 unused Assets to reduce memory usage. Loaded Objects now: 4388.
Total: 11.266681 ms (FindLiveObjects: 0.379151 ms CreateObjectMapping: 0.069300 ms MarkObjects: 10.693607 ms  DeleteObjects: 0.124353 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 14 unused Assets to reduce memory usage. Loaded Objects now: 4598.
Total: 11.245802 ms (FindLiveObjects: 0.332734 ms CreateObjectMapping: 0.042700 ms MarkObjects: 10.852555 ms  DeleteObjects: 0.017563 ms)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_93.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_116.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_135.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_142.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_99.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_124.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_127.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_103.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_90.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_117.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_108.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_131.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_146.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_140.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 41 unused Assets to reduce memory usage. Loaded Objects now: 4732.
Total: 11.169099 ms (FindLiveObjects: 0.329809 ms CreateObjectMapping: 0.042770 ms MarkObjects: 10.768157 ms  DeleteObjects: 0.028113 ms)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_139.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_140.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_141.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)
Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_142.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_135.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_93.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_99.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_103.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_116.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_140.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_127.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_124.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_90.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_117.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_131.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_108.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_146.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)


Unloading 14 unused Assets to reduce memory usage. Loaded Objects now: 4730.
Total: 11.240372 ms (FindLiveObjects: 0.323527 ms CreateObjectMapping: 0.043561 ms MarkObjects: 10.855000 ms  DeleteObjects: 0.018114 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 21 unused Assets to reduce memory usage. Loaded Objects now: 4730.
Total: 12.791652 ms (FindLiveObjects: 0.461696 ms CreateObjectMapping: 0.073197 ms MarkObjects: 12.237091 ms  DeleteObjects: 0.019337 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 21 unused Assets to reduce memory usage. Loaded Objects now: 4730.
Total: 11.338486 ms (FindLiveObjects: 0.327605 ms CreateObjectMapping: 0.043271 ms MarkObjects: 10.945760 ms  DeleteObjects: 0.021610 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)
Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_13.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_23.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_34.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_32.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_65.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_45.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_69.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_53.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_62.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)


Unloading 14 unused Assets to reduce memory usage. Loaded Objects now: 4775.
Total: 12.724756 ms (FindLiveObjects: 0.339256 ms CreateObjectMapping: 0.049011 ms MarkObjects: 12.313114 ms  DeleteObjects: 0.023033 ms)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_19.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_2.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_74.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_60.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_38.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_49.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_28.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_77.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)
Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_70.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_69.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_72.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_71.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)


Unloading 41 unused Assets to reduce memory usage. Loaded Objects now: 4820.
Total: 12.289089 ms (FindLiveObjects: 0.423273 ms CreateObjectMapping: 0.076002 ms MarkObjects: 11.761660 ms  DeleteObjects: 0.027933 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)
Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_23.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_65.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_34.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_13.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_32.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_62.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_53.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_2.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_19.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_45.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_38.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_60.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_69.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_49.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_74.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_28.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_77.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)


Unloading 14 unused Assets to reduce memory usage. Loaded Objects now: 4818.
Total: 11.435748 ms (FindLiveObjects: 0.322074 ms CreateObjectMapping: 0.043782 ms MarkObjects: 11.050446 ms  DeleteObjects: 0.019065 ms)

Unloading 1 Unused Serialized files (Serialized files now loaded: 0)

Unloading 21 unused Assets to reduce memory usage. Loaded Objects now: 4818.
Total: 13.622079 ms (FindLiveObjects: 0.385213 ms CreateObjectMapping: 0.044163 ms MarkObjects: 13.157097 ms  DeleteObjects: 0.035256 ms)

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Upgrade_109.png
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
`

**Comment by rune-b** [comment] 2020-01-28 16:57
That's strange. The underlying error message should have been logged after the "Cannot download image..." line now :(

**Comment by jayhags** [comment] 2020-02-07 01:18
I have noticed the same issue on my Fedora system, but the avatars load on my Ubuntu system.

The error message from my Player.log includes the extra message:

Cannot download image: https://sb-cdn.fantasyflightgames.com/card_images/Card_Pilot_117.png
Unable to complete SSL connection 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

I though it was possibly due to the trusted certificates list on each system.  But checking with **trust list** on both systems, the have similar defaults and include the AWS certificates which see to be where the pngs are located.

**Comment by nix-7** [comment] 2020-02-07 09:41
Well it does get further than before, which wouldn't even attempt a TLS handshake.
Now the handshake occurs, but fails after receiving the certificate;
![image](https://user-images.githubusercontent.com/57040380/74018163-4f6d4900-498d-11ea-9aba-378472fa28ff.png)

However the cert is valid (obviously), and works fine in curl/firefox/chromium...

Looking in the Player.log I'm getting more info;
-------------
Cannot download image: https://images-cdn.fantasyflightgames.com/filer_public/6c/73/6c73ec27-bf29-4ace-86e9-4d03cdafa884/swz48_pilot-shadow-vet.png
Unable to complete SSL connection 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Curl error 35: Cert handshake failed. verify result: UNITYTLS_X509VERIFY_FATAL_ERROR. error state: 7
 
(Filename:  Line: 808)
---------------
Does Unity use it's own CA store???

BTW I am not doing any TLS interception to mess with certs.

**Comment by rune-b** [comment] 2020-02-09 21:09
Note that Unity doesn't officially support other linux distros than Ubuntu:
https://docs.unity3d.com/2019.3/Documentation/Manual/system-requirements.html?_ga=2.39247463.535475406.1581282238-493568148.1578064299#desktop

There is some discussion of this error here:
https://forum.unity.com/threads/ubuntu-headless-build-tls-handshake-fails.546704/

**Comment by rune-b** [comment] 2020-02-09 21:10
Here is a possible solution. Please report back if you try it

https://stackoverflow.com/questions/53597396/why-does-unitywebrequest-return-unkown-error-when-i-do-a-get-request-on-linux

**Comment by jayhags** [comment] 2020-02-09 21:24
Adding the link as described worked on my Fedora 31 system.  The only failed image in my Player.log was also a 404 not found via web browser

`HTTP/1.1 404 Not Found 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Cannot download image: https://raw.githubusercontent.com/guidokessels/xwing-data/master/images/upgrades/Crew/admiral-sloane.png
Texture has not yet finished downloading 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
`

**Comment by nix-7** [comment] 2020-02-10 08:01
Unity was indeed using a different location for it's CA store. Or more likely it's expecting it in Ubuntu's default location, not Fedora's.

So I can confirm that linking to the correct location resolves the issue on Fedora 31;

`` # ln -s /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt ``

Thanks for helping sort this!

**Comment by rune-b** [comment] 2020-02-10 09:41
#leoarthur83 can you try this and see if it works on your Open Suse machine too?

**Comment by rune-b** [comment] 2020-02-23 20:12
Will close this issue now. #leoarthur83: if the solution above doesn't work for you, please re-open.

I have made a new wiki page with info about running the game on linux and known problems/fixes, and have added this issue there. Please let us know if there are other linux related issues that should be included in this page

https://github.com/Sandrem/FlyCasual/wiki/How-to-run-Fly-Casual-on-linux

**Closed by rune-b** 2020-02-23 20:12 UTC
