### ISSUE TITLE
0.5.1.  ai vader just sat after it said he could perform second cluster missile attack.......

### ISSUE THREAD

**Issue by drdov** [Sandrem/FlyCasual#1028] opened 2018-06-29 03:45 UTC
Game got stuck

**Comment by Sandrem** [comment] 2018-07-07 19:21
Cannot reproduce. Please, next time provide screenshot of situation.

**Comment by raithos** [comment] 2018-07-11 05:02
I just had this happen to me as well. happened vs ai. vader went to shoot and did nothing. his first attack was not cluster missles

**Comment by Sandrem** [comment] 2018-07-11 05:05
Please, attach screenshots when reporting bugs.

If no error is shown, open console manually (CTRL + ~).

**Comment by raithos** [comment] 2018-07-11 05:11
Restarted the match to get the screenshot. This happened in 0.5.2, 2nd edition we just went for the initial engagement and now stuck. 
![ss 2018-07-11 at 01 09 01](https://user-images.githubusercontent.com/25230261/42551802-2d096968-84a7-11e8-88a6-e9afa1bea797.jpg)

**Comment by raithos** [comment] 2018-07-11 05:18
Also, this happened when vader was performing a primary attack, not a cluster missles attack. The trigger on cluster missles itself is a problem because it triggers whether or not the first attack was cluster missles

**Comment by CaptainJaguarShark** [comment] 2018-08-04 05:27
I also face this issue in 0.5.3 hotfix 1

Vader attacked an a-wing on first round of battle, then gameplay stuck. Vader remains highlighted in green and a new attacker was not selected by AI.

![vader missiles fail](https://user-images.githubusercontent.com/2208847/43672865-e33e2de4-977c-11e8-902b-37c35eba3400.PNG)

**Comment by rune-b** [comment] 2018-08-20 17:36
I also got this error in latest dev branch:
![image](https://user-images.githubusercontent.com/11047987/44356682-55791c80-a4b0-11e8-8634-aba7c8f3615f.png)

**Comment by Sandrem** [comment] 2018-08-31 17:10
Will be fixed in 0.6.2
I close this issue as duplicate of https://github.com/Sandrem/FlyCasual/issues/1082

**Closed by Sandrem** 2018-08-31 17:10 UTC
Labels: Cannot reproduce
