### ISSUE TITLE
Fifth Brother ability error

### ISSUE THREAD

**Issue by K1ngUnd3ad** [Sandrem/FlyCasual#2753] opened 2020-06-16 03:18 UTC
![image](https://user-images.githubusercontent.com/66984914/84728072-6d137600-af5e-11ea-9645-519a8902f152.png)

when using Fifth Brother pilot ability in conjunction with homing missle, an error caused the game to crash

**Comment by grandpajive** [comment] 2020-06-16 15:34
Same thing happens if you choose not to use the force to change a homing missile hit to a crit

**Comment by Sandrem** [comment] 2020-06-19 20:22
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2668

**Closed by Sandrem** 2020-06-19 20:22 UTC
