### ISSUE TITLE
Twin Laser Turret Won't Fire Out of Arc

### ISSUE THREAD

**Issue by cmarzipan** [Sandrem/FlyCasual#590] opened 2018-02-05 06:56 UTC
Attempted to fly TIE Aggressors with TLT but they could not declare a target outside of their firing arcs. Awesome work on the game so far! Just playing the AI is helping me play better!

**Comment by Sandrem** [comment] 2018-02-05 06:58
Try to measure distance using right mouse button before shot. Maybe range was 1 or more than 3.
Also, in such cases provide screenshots.

**Comment by Sandrem** [comment] 2018-02-05 07:01
Just checked - TIE Aggressor successfully attacked enemy ship with TLT ouside of his arc. So more information about how to reproduce this problem is needed.

**Comment by MrRollyPanda** [comment] 2018-02-11 21:36
I had the same issue with TLT on KWing and H-6 Scourge.

Cannot reproduce it yet.

**Comment by MrRollyPanda** [comment] 2018-02-18 10:06
TLT error again, whilst using y-wings.

It was approx round 4. 

2 of the Y-Wings used TLT successfully, 2 of them were not prompted to use the option. One auto-fired with primary, the last could not shoot.

![outsidearc](https://user-images.githubusercontent.com/36319740/36350592-138f15be-14ef-11e8-87c4-700e8d250726.PNG)

**Comment by Sandrem** [comment] 2018-02-18 11:02
TLT is range 2-3 only.
As I see on screenshot, distance between ships is range 1. So TLT cannot be used in this case.

Closed as not a bug.

**Closed by Sandrem** 2018-02-18 11:02 UTC
Labels: Cannot reproduce
