### ISSUE TITLE
K-Wing - cannot fire Barrage rockets while primary turret is side facing

### ISSUE THREAD

**Issue by neadcb** [Sandrem/FlyCasual#1280] opened 2018-10-19 03:00 UTC
Game will not allow barrage rockets (did not confirm other ordinance) from front arc while primary turret is pointed left / right.

**Comment by Sandrem** [comment] 2018-10-23 16:07
Duplicate of https://github.com/Sandrem/FlyCasual/issues/1269

**Closed by Sandrem** 2018-10-23 16:07 UTC
