### ISSUE TITLE
Fifth Brother special ability crashed game

### ISSUE THREAD

**Issue by starjoe4** [Sandrem/FlyCasual#2758] opened 2020-06-17 19:43 UTC
Had this crash twice in a row (first time I used Fifth Brother's ability in each of two games in a row)

![image](https://user-images.githubusercontent.com/47924192/84942672-3601a980-b0b1-11ea-8fac-3808e00d3c1f.png)

**Comment by Sandrem** [comment] 2020-06-19 20:25
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2668

**Closed by Sandrem** 2020-06-19 20:25 UTC
