### ISSUE TITLE
Error after AI tries to activate Merciless Pursuit

### ISSUE THREAD

**Issue by Korran12** [Sandrem/FlyCasual#3337] opened 2021-09-11 05:18 UTC
![Captura de pantalla 2021-09-11 00 17 49](https://user-images.githubusercontent.com/67489605/132937176-09444d63-853a-4eb2-bb63-d9a905e8fdf2.png)

**Comment by Sandrem** [comment] 2021-11-15 18:26
Closed as duplicate of #3339

**Closed by Sandrem** 2021-11-15 18:26 UTC
