### ISSUE TITLE
"Rush" Not Engaging When Skill Increased

### ISSUE THREAD

**Issue by mingodave42** [Sandrem/FlyCasual#3033] opened 2020-12-04 21:10 UTC
When played by the AI, "Rush" (First Order TIE/vn) does not engage when its pilot skill jumps from 2 to 6. I got a message that "Rush will activate after all initiative 3 ships have engaged" but just sat there when that happened.

**Comment by Sandrem** [comment] 2020-12-08 18:12
I tested few scenarios, where "Rush" was controlled both by the AI and real player - I cannot reproduce a situation where "Rush" didn't activate after initiative is changed (exception: when this pilot is already activated).
Please, provide steps to reproduce this bug with 100% chance, otherwise I will close it if I cannot get a way to reproduce this situation.

**Comment by mingodave42** [comment] 2020-12-08 18:38
Sandrem-
That makes sense. Give me a day or so to see if I can get it to happen
again, and then feel free to close it if you haven't heard from me. (By the
way, I also got the glitch in the attached screenshot, but that may have
been fixed in the latest version.)
David

**Comment by Sandrem** [comment] 2020-12-08 18:42
> By the way, I also got the glitch in the attached screenshot, but that may have been fixed in the latest version

I don't see any attached screenshots in this issue.
Anyway, please, create separate issue for each separate bug / glitch. Otherwise I have problems with management of open / fixed bugs.

**Comment by mingodave42** [comment] 2020-12-08 18:53
Sandrem-
I was able to hit the glitch again. Squads in play are as shown. So far, as
soon as Rush is damaged, it hangs at the end of the initiative 3 combat
phase. I'll start a new game and see if I can reproduce.
David


[image: image.png]

**Comment by mingodave42** [comment] 2020-12-08 19:13
Sandrem-
Here are my steps.
David

1. Start "Fly Casual"
2. New Game, Versus AI
3. Load squad player 1 (autosave: Lyttan Dree + Synced Laser Cannons +
Maneuver-Assist MGK-300 + Hull Upgrade; Howlrunner + Composure; Black
Squadron Ace + Deadeye Shot; Black Squadron Ace + Crack Shot; Black
Squadron Ace + Deadeye Shot; Valen Rudor + Deadeye Shot)
4. Load or customize squad, AI player 2 (Major Vonreg, Rush, Backdraft,
Quickdraw)
5. Random obstacle placement
6. Setup in opposite corner from AI
7. Play, taking targets of best opportunity. Usually I kill Backdraft or
Quickdraw.
[image: image.png]
8. Game hangs at end of activation phase when Rush is damaged (in this
image, I hit Rush with Howlrunner, and the game stops when initiative
should move to 3)
[image: image.png]

**Comment by Sandrem** [comment] 2020-12-08 19:14
Thank you, I will check

**Comment by Sandrem** [comment] 2021-07-09 17:26
Some fixes are done

**Closed by Sandrem** 2021-07-09 17:26 UTC
Labels: Cannot reproduce
