### ISSUE TITLE
Advanced Sensors

### ISSUE THREAD

**Issue by Senzorezo** [Sandrem/FlyCasual#1241] opened 2018-09-17 19:05 UTC
Hi,

the upgrade ADVANCED SENSORS does not allow a second action in the same activation.
So it is impossible to DOUBLE-ACTION when using this upgrades.

Thanks a lots for your work !

**Comment by Sandrem** [comment] 2018-09-17 19:19
Duplicate of https://github.com/Sandrem/FlyCasual/issues/1177
Will be fixed as part of that issue. Closed.

**Closed by Sandrem** 2018-09-17 19:19 UTC
