### ISSUE TITLE
Attack does not resolve sometime in 0.2.1

### ISSUE THREAD

**Issue by Trokinos** [Sandrem/FlyCasual#293] opened 2017-10-25 18:50 UTC
I have been having lots of fun battles testing various ships configurations in the current 0.2.1 release and i had a couple of time the game that didn't continue after an attack (and maybe a defense) roll.

When it happened in an earlier battle, while i don't remember exactly the ships configuration (out of having 3 X-Wing, one with Luke and one with with Biggs) , but this time i thought about screenshoting the screen so ships configurations can be noticed, here's the screenshot 

https://i.imgur.com/xQR1ide.jpg

I was playing on the empire side with a tie advanced to test some of the equipment available to it and took a shot to the scum ship (the advanced torpedo was fired earlier and did their job without problem occuring)
While you can still move the camera all around the battlefield, the game is stuck there, the attack roll has been done but there's no defense roll happening and nothing else can be done out of quitting the game.

**Comment by Sandrem** [comment] 2017-10-25 19:19
Thank you for information.
Second player is a human or an AI ?

**Comment by Trokinos** [comment] 2017-10-25 19:20
It was AI

**Comment by Sandrem** [comment] 2017-11-12 11:49
Bug is caused by Guidance Chips if you attack not with missile/torpedo.
Fixed in development branch, will be in 0.3.0

**Closed by Sandrem** 2017-11-12 11:49 UTC
Labels: bug
