### ISSUE TITLE
Issue with tractor

### ISSUE THREAD

**Issue by starjoe4** [Sandrem/FlyCasual#2901] opened 2020-09-01 18:52 UTC
When using Captain Phasma to give a stress then Petty Officer Thanisson to tractor, a game-stopping error occurs.  This does not seem to be dependent on whether the tractored ship is moved onto an obstacle or not.  Hopefully the attachment worked - 
[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/5158246/LastReplay.zip)

**Comment by otuv** [comment] 2020-09-01 19:40
![Screenshot from 2020-09-01 21-39-38](https://user-images.githubusercontent.com/16488095/91898215-b2149200-ec9b-11ea-966e-85d54ea61798.png)
And here is the stacktrace. Onto an object in this case.

**Comment by rune-b** [comment] 2020-09-12 15:53
Duplicate of #2883. Closing this

**Closed by rune-b** 2020-09-12 15:53 UTC
