### ISSUE TITLE
Game gets stuck when attempting to use countess ryad's ability  

### ISSUE THREAD

**Issue by RedRaspberry** [Sandrem/FlyCasual#1186] opened 2018-08-30 18:04 UTC
See title, not much to describe

It just sits there waiting to move, but it doesn't perform the move.

**Comment by Sandrem** [comment] 2018-08-31 12:40
Duplicate of https://github.com/Sandrem/FlyCasual/issues/1175

**Closed by Sandrem** 2018-08-31 12:40 UTC
