### ISSUE TITLE
Synchronized console does not proc after bonus attacks

### ISSUE THREAD

**Issue by dherve10** [Sandrem/FlyCasual#1826] opened 2019-04-19 16:22 UTC
The upgrade only seems to allow for reassignment of target locks after the initial attack, but does not give the option after the bonus attack from cluster missiles. I presume this is also true for bonus attacks from other sources.

**Comment by bitsai** [comment] 2019-07-17 21:56
I don't think this was a bug; Synchronized Console's ability only works if you have a lock on the target being attacked.  Cluster Missiles require a lock on the original target, so the bonus attack's target would not have had a lock (because Sync Console is Republic-only, and Republic currently doesn't have any ships that can carry Cluster Missiles **AND** maintain locks on more than 1 target), and so there was no lock for Synchronized Console to reassign on the bonus attack.

If you run into a situation where Synchronized Console failed to trigger during a bonus attack on a target you do have a lock on, please feel free to re-open this (and if possible, please add screenshots and steps to reproduce).  Thanks!

**Closed by bitsai** 2019-07-17 21:56 UTC
Labels: Cannot reproduce
