### ISSUE TITLE
Interceptor barrel roll

### ISSUE THREAD

**Issue by doji2008** [Sandrem/FlyCasual#1199] opened 2018-09-01 16:51 UTC
Game crashes as soon as i barrel role. Does not seem to matter if it is a white barrel roll off the first action or as a red off the combo.

Using android device.

**Comment by doji2008** [comment] 2018-09-01 16:53
![screenshot_20180901-093839_fly casual x-wing tmg simulator](https://user-images.githubusercontent.com/37707411/44948094-c7186b00-adcc-11e8-8a3e-b2d3086a2f4c.jpg)
![screenshot_20180901-095128_fly casual x-wing tmg simulator](https://user-images.githubusercontent.com/37707411/44948097-d13a6980-adcc-11e8-82a7-27e7e0a248fa.jpg)

**Comment by doji2008** [comment] 2018-09-01 16:59
![screenshot_20180901-095819_fly casual x-wing tmg simulator](https://user-images.githubusercontent.com/37707411/44948159-aef51b80-adcd-11e8-9d11-b242ee32601f.jpg)
Actually i guess it is any ship i barrel roll with.

**Comment by rune-b** [comment] 2018-09-03 19:35
Duplicate of #1125

**Comment by Sandrem** [comment] 2018-09-11 06:09
Was fixed

**Closed by Sandrem** 2018-09-11 06:09 UTC
Labels: duplicate
