### ISSUE TITLE
[0.9.2] VTG turret attack is delayed by 2-3 seconds

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#2071] opened 2019-07-14 13:52 UTC
That's it.

**Comment by bitsai** [comment] 2019-07-14 15:50
I flew a mirror match against AI using 2 Finch Dallow's, both with Paige Tico, Proton Bombs, and Veteran Turret Gunner.  There was no discernible delay on the VTG attacks for both AI and myself.

What were the 2 lists where you saw the 2-3 second delay on VTG attacks?  Was Dynamic Camera enabled at the time (I have it off)?  Also, what kind of device were you playing on (I'm on my laptop)?

**Comment by Nitroxylin** [comment] 2019-07-14 16:03
My list:
 - Finch (Paige, VTG, proton bombs, delayed fuses, advanced optics, FCS, perceptive copilot)
 - Cat (same, but with Rey instead of Page)
Enemy list:
 - 4-skill Fang swarm

Dynamic camera: on
Device: ASUS K501L

**Comment by Sandrem** [comment] 2019-07-14 17:34
Seems that this is caused by Dynamic Camera - it takes few seconds to change position. So if attacker and defender are same, it just waits for few seconds.

**Comment by bitsai** [comment] 2019-07-14 17:35
Yeah, when replaying the specified match-up, that's the only significant delay I saw for VTG.

**Comment by bitsai** [comment] 2019-07-14 17:37
@Nitroxylin as mentioned in #2070, if you feel like the Dynamic Camera is too inconvenient, you can turn it off by going to Options -> Extra from the main menu.

**Comment by bitsai** [comment] 2019-07-15 09:17
I'm gonna classify this as a specific instance of the general issue tracked in #2070, closing.

**Closed by bitsai** 2019-07-15 09:17 UTC
Labels: Cannot reproduce
