### ISSUE TITLE
Homing Missile fired at AI causes game crash

### ISSUE THREAD

**Issue by desertowl1026** [Sandrem/FlyCasual#2797] opened 2020-07-05 17:29 UTC
<img width="1440" alt="Untitled" src="https://user-images.githubusercontent.com/67872473/86538271-ef31f300-bea9-11ea-8b5e-ea4b9dbaf056.png">
I fired homing missiles at Mace Windu; he accepted the automatic damage but then the game crashed.

**Comment by Sandrem** [comment] 2020-07-06 10:39
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2668

**Closed by Sandrem** 2020-07-06 10:39 UTC
