### ISSUE TITLE
Game crash when try to use target lock with Wedge

### ISSUE THREAD

**Issue by Blastanoid** [Sandrem/FlyCasual#381] opened 2017-12-02 18:43 UTC
Hi,
when I use Wedge Antilles, everytime I try to use the ability Target Lock after the dice launch, the game crash. This happen when there are lots of ship on table. 
I attach the debug windows that appear when the issue happen
![cattura](https://user-images.githubusercontent.com/34194381/33518663-10d94c10-d799-11e7-8db0-786a0aec861c.JPG)

**Comment by Sandrem** [comment] 2017-12-05 14:28
What mode/opponent is in this game? AI, local opponent or network opponent?
(maybe bug is caused by R5-K6)

**Comment by Blastanoid** [comment] 2017-12-05 17:27
Hi Sandrem,
The opponent was AI 
I'll try to use another droid and I let you if the bug is gone.

Carlo 

Inviato da iPad

**Comment by Blastanoid** [comment] 2017-12-06 19:36
Yes, you are absolutely right, the bug is connected to R5-K6 (damn droid)

**Comment by Sandrem** [comment] 2017-12-08 01:36
R5-K6 is fixed in development branch

**Closed by Sandrem** 2017-12-08 01:36 UTC
Labels: bug
