### ISSUE TITLE
Zam Wessel, P2P

### ISSUE THREAD

**Issue by aderius** [Sandrem/FlyCasual#3155] opened 2021-02-13 19:27 UTC
Situation:
1. Player with Zam Wessell 
2. End of combat, 0 tokens on Zam
3. Still asks if you want to bonus attack
4. If you click yes, nothing happens and it also cannot be skipped

**Comment by Sandrem** [comment] 2021-02-14 09:28
Duplicate of https://github.com/Sandrem/FlyCasual/issues/3156

**Closed by Sandrem** 2021-02-14 09:28 UTC
