### ISSUE TITLE
Corran Horn NullReferenceException

### ISSUE THREAD

**Issue by r4dian** [Sandrem/FlyCasual#1909] opened 2019-05-30 13:37 UTC
Happens everytime at the end of combat on the 1st turn when Corran Horn is present
[SavedSquadrons - Copy.zip](https://github.com/Sandrem/FlyCasual/files/3237242/SavedSquadrons.-.Copy.zip)

Version 0.8.2, Windows 10.
[Player.log](https://github.com/Sandrem/FlyCasual/files/3237208/Player.log)

**Comment by bitsai** [comment] 2019-06-18 06:34
While developing & testing the Corran Horn fix (https://github.com/Sandrem/FlyCasual/pull/1928), I was not able to reproduce this behavior in the current development branch.

**Comment by rune-b** [comment] 2019-06-23 19:18
Just tried this with your two saved squadrons, but got no error at the end of combat

Did you play hotseat or vs AI? Did you have any shooting in the first round?

**Comment by r4dian** [comment] 2019-06-24 09:11
VS AI, with Corran on the AI team.
I don't have to shoot in the 1st round to repro it.

**Comment by rune-b** [comment] 2019-06-24 12:37
Have you tried with the latest version?

**Comment by Sandrem** [comment] 2019-06-28 07:50
Cannot reproduce in current dev-version

**Comment by r4dian** [comment] 2019-07-01 17:24
Still occurs in 0.9.1.1

**Comment by bitsai** [comment] 2019-07-01 18:49
@r4dian I just tested the 0.9.1.1 release using your saved squads (me playing Scum and AI playing Rebels), but there was no crash/error at the end of the first round.

Can you please provide more details on your initial setup (for example, where did you deploy your ships, and which maneuvers were dialed in) and screenshot(s)?

**Comment by rune-b** [comment] 2019-07-01 20:01
@r4dian Are you using any mods? If so, which?

Do you get the error if you play with other squads including Corran? Could you try playing a single generic ship against lone AI Corran?

**Comment by rune-b** [comment] 2019-07-01 20:15
Just managed to reproduce this while debugging. Didn't happen the game before when I wasn't debugging... Don't know yet what triggers it, but at least we now know exactly where in the code it crashes

![image](https://user-images.githubusercontent.com/11047987/60463982-a8ce0680-9c4d-11e9-8718-a62d061910e2.png)

**Comment by rune-b** [comment] 2019-07-01 20:24
Reproduced again, without AI this time. Single Bandit Squadron vs. Corran. No upgrades.

Turn 1: Z-95 does 1 straight. Corran does 5 straight. Crashes at the end of combat phase

![image](https://user-images.githubusercontent.com/11047987/60464421-d5cee900-9c4e-11e9-854f-4d61122a5658.png)

**Comment by rune-b** [comment] 2019-07-01 20:29
Replay: 
[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/3347228/LastReplay.zip)

**Comment by bitsai** [comment] 2019-07-07 18:26
@rune-b do you mind checking to see if this is still happening in the latest development branch?  I just tested using the steps from above (Z-95 1-straight, Corran 5-straight), but there was no crash at the end of the combat phase for me.

**Comment by rune-b** [comment] 2019-07-08 08:16
I am currently in the middle of moving, so I don't have much spare time at the moment, but will try to reproduce it again when I have the opportunity

I did try to reproduce it on my phone a couple of days ago with the latest release, but did not get any errors there

**Comment by bitsai** [comment] 2019-07-08 16:59
@rune-b thank you, and good luck w/ the move!

**Comment by rune-b** [comment] 2019-07-14 11:51
I have tried many times now to reproduce it again, but no success...

Must be something we're missing. Or this bug has been fixed

**Comment by bitsai** [comment] 2019-07-14 12:12
Cool!  I will optimistically close this one for now; we can of course re-open it if this ever pops up again.

**Closed by bitsai** 2019-07-14 12:12 UTC
Labels: Cannot reproduce
