### ISSUE TITLE
Error While Thane Kyrell's special being picked

### ISSUE THREAD

**Issue by ThomRiddle88** [Sandrem/FlyCasual#2738] opened 2020-06-09 15:36 UTC
I applied Thane Kyrell's talent to a Panicked Pilot card (I think) and then this error popped up.
![image](https://user-images.githubusercontent.com/64228824/84168727-5c826d80-aa3d-11ea-953e-36df705b532d.png)

**Comment by Sandrem** [comment] 2020-06-26 23:39
Thank you.

Duplicate of https://github.com/Sandrem/FlyCasual/issues/2764

**Closed by Sandrem** 2020-06-26 23:39 UTC
