### ISSUE TITLE
Major Rhymer's ability doesn't work with multi-missile pods.

### ISSUE THREAD

**Issue by pdelgado248** [Sandrem/FlyCasual#3190] opened 2021-03-02 17:45 UTC
When trying to shoot multi-missile pods from Major Rhymer (TIE bomber), it doesn't allow me to choose enemies at range 3, as it should thanks to his ability of increasing and decreasing range restrictions of missiles or torpedoes. It also lets me fire the missiles without a target lock.

**Comment by Sandrem** [comment] 2021-03-02 21:11
Duplicate of https://github.com/Sandrem/FlyCasual/issues/3104

**Closed by Sandrem** 2021-03-02 21:11 UTC
