### ISSUE TITLE
Attacking with Homing missiles at range three, Attacker, RZ-2 A wing, Defender, E wing

### ISSUE THREAD

**Issue by CameronBajus** [Sandrem/FlyCasual#2747] opened 2020-06-12 07:31 UTC
![xwingbug](https://user-images.githubusercontent.com/15381986/84477161-36d3af00-ac5d-11ea-9382-26c42b7c0d1e.PNG)

**Comment by Sandrem** [comment] 2020-06-19 20:17
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2668

**Closed by Sandrem** 2020-06-19 20:17 UTC
