### ISSUE TITLE
Wedge final attack then death crash [bug] [ship destruction]

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#1905] opened 2019-05-29 02:18 UTC
Wedge was killed by Poe Dameron.  He got to make his final attack, and had a target lock token on him because Poe didn't have to spend it on his attack.  Then the game crashed trying to remove the target lock token from the now non-existent Wedge.  Here's a picture of the messages.  I suspect this is related to the Resistance Chewbacca bug as well.
![Wedge Death bug](https://user-images.githubusercontent.com/48073298/58524517-b5120000-8185-11e9-81fa-a15185b527bb.png)

**Comment by Sandrem** [comment] 2019-05-29 02:22
Please, don't forget to mention what version of game do you use. (I know that this is dev-build because of Stats button).
As I know, this bug is only in dev-branch, caused by my changes in TL tokens to allow lock on obstacles.
Seems that it is caused by destruction of any ship with red target lock.

**Comment by Sandrem** [comment] 2019-05-29 02:26
If you have free time, you can fix this: go to RedTLToken class, undo my changes in constructor.
Revert my changes of Host - it must have GenericShip Host value (See BlueTLToken code as example). If is is assigned to asteroid - lease Host as null. I think that will work. Just test work of Qi'Ra after this too.

**Comment by DejaFu** [comment] 2019-05-29 05:17
I’ll check it out tomorrow.
 - Donner

**Comment by Sandrem** [comment] 2019-05-30 04:04
Fixed

**Closed by Sandrem** 2019-05-30 04:04 UTC
