### ISSUE TITLE
Gunner Luke Skywalker interacts with the normal action "Turret Rotation"

### ISSUE THREAD

**Issue by Senzorezo** [Sandrem/FlyCasual#2154] opened 2019-08-04 15:08 UTC
Hi.

When you do the action "Turret Rotation" in the stand action phase, the Force point is spent.
And, somtimes, the Force point is spent for no reason (after a upgraded boost for example)

Tested on YT1300 - Han solo Pilot.

**Comment by bitsai** [comment] 2019-08-08 03:23
I tested this using Han Solo YT-1300 + Luke gunner + Engine Upgrade vs. an AI TIE Fighter, but wasn't able to reproduce the problems no matter what combination of turret rotating and boosting I did.

Could you try to reproduce the problem, and provide the steps needed to reproduce?  Also, screenshot(s) of your squad and the enemy squad can be very helpful, because oftentimes the problem is caused by interactions between multiple things.  Thanks!

**Comment by Senzorezo** [comment] 2019-08-08 07:53
Turn 1 : made a 4 straight and a boost as a standard action : No problem.
Turn 2 : made a 1 straight and a turret rotation as a standard action : 1 Force was spent.

![image](https://user-images.githubusercontent.com/35725438/62685045-2cec7a00-b9c2-11e9-8036-eb367612280b.png)

**Comment by bitsai** [comment] 2019-08-08 08:05
Thank you for the detailed info!  Using the steps you provided, I was able to reproduce the problem in release 0.9.2.

Good news!  The problem is already fixed in the latest development branch.  I'm going to optimistically close this, but please feel free to re-open this if you see this pop up again in the upcoming release.  Cheers!

**Closed by bitsai** 2019-08-08 08:05 UTC
Labels: Cannot reproduce
