### ISSUE TITLE
Pilots cards rendering error on Asus tablet (Android)

### ISSUE THREAD

**Issue by elsapo70** [Sandrem/FlyCasual#2772] opened 2020-06-24 12:09 UTC
Error message is thrown while rendering pilots cards images. The png files are properly stored in the ImageCache folder. It's not a network issue. Clearing the cache does not help.

Screen resolution is 2048x1536.

![Screenshot_2020-06-24-13-52-34](https://user-images.githubusercontent.com/36621235/85552964-cf860980-b623-11ea-9b93-704922552f03.jpg)

**Comment by Sandrem** [comment] 2020-06-26 22:25
As I see code - such error can be show if downloaded images are corrupted (width / height are detected as 0).
Or maybe something blocks access to downloaded images?

I checked in Unity with custom screen with mentioned resolution, also checked on few Andoid devices (including 10'1 tablet, but not ASUS) - I cannot reproduce this error.

Please, try to "Clear all data" (not only Cache). Or try to delete images manually (./Android/Data/com.sandrem.flycasual/files/)

**Closed** 2021-06-18 13:58 UTC
Labels: Cannot reproduce
