### ISSUE TITLE
Generic YV666 movement caused NRE crash.

### ISSUE THREAD

**Issue by jamesrhum** [Sandrem/FlyCasual#2711] opened 2020-06-03 13:42 UTC
AI Ship appears to be doing a 2 turn right.
![fly_casual_bug](https://user-images.githubusercontent.com/66371287/83643831-70931e80-a5a8-11ea-9442-a9fb7806d0de.jpg)

[LastReplay.replay.txt](https://github.com/Sandrem/FlyCasual/files/4723700/LastReplay.replay.txt)

**Comment by Sandrem** [comment] 2020-06-27 00:36
Thank you for replay

Duplicate of https://github.com/Sandrem/FlyCasual/issues/2773

**Closed by Sandrem** 2020-06-27 00:36 UTC
