### ISSUE TITLE
Outmanoeuvre not triggering

### ISSUE THREAD

**Issue by Ubergod** [Sandrem/FlyCasual#1697] opened 2019-03-28 14:11 UTC
L'ulo L'ampar with outmanoeuvre doesn't cause enemy ships to lose a defence dice.

**Comment by rune-b** [comment] 2019-03-28 15:17
There has been some debate on whether Outmaneuver works at all with ships that only have turret arcs. Has there been an official ruling on this?

**Comment by rune-b** [comment] 2019-03-28 16:04
This ruling on Kavil makes me think that Outmaneuver should not work on RZ2 Awings, except if they shoot a missile eith standard arc

https://community.fantasyflightgames.com/topic/277390-x-wing-official-rulings/?do=findComment&comment=3491377

**Comment by Sandrem** [comment] 2019-03-28 17:07
This conversation confirms that Outmaneuver doesn't work with RZ-2 A-Wing:
https://www.reddit.com/r/XWingTMG/comments/a72teb/rules_question_outmaneuver_on_rz2_awings/

For developers: We need to check cards with similar restrictions. As I remember, I used "if target is in front sector, then", but we need to use "If current attack if perfromed from front arc, them."

**Comment by rune-b** [comment] 2019-03-28 20:40
The strange thing is that one of the quick build cards for the RZ-2 has Outmaneuver and Proton Rockets... So I wouldn't be surprised if there comes an errata that allows Outmaneuver after all

**Comment by rune-b** [comment] 2019-04-10 07:01
Closing this since it is not a bug

**Closed by rune-b** 2019-04-10 07:01 UTC
