### ISSUE TITLE
Ten Numb

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#1971] opened 2019-06-26 00:43 UTC
> When I used Ten Numbʻs ability (Rebel B-Wing) game provided an error.
> Mac build, my OS is Mojave 10.14.4.

Source: https://www.reddit.com/r/XWingTMG/comments/c3d0w1/fly_casual_version_090/es1tkg9/

**Comment by Sandrem** [comment] 2019-06-26 01:20
https://i.imgur.com/9qRzQrQ.jpg

**Comment by rune-b** [comment] 2019-06-26 06:36
I did not getting any errors when using his ability. Screenshot is too blurry to make out which other upgrades were in use

**Comment by bitsai** [comment] 2019-07-08 16:56
Re-tested this in latest development branch, still was not able to reproduce the error, closing for now.

**Closed by bitsai** 2019-07-08 16:56 UTC
Labels: Cannot reproduce
