### ISSUE TITLE
Automated Targetting Priority crash

### ISSUE THREAD

**Issue by Hallaore** [Sandrem/FlyCasual#3287] opened 2021-06-03 19:17 UTC
![automated target priority error](https://user-images.githubusercontent.com/84185432/120699181-fab9df80-c4a7-11eb-8787-b3d6235be687.png)
Hi there

I think there's an issue with the AI using the Automated Targeting Priority upgrade. I think what's happening is the AI selects a target that conflicts with ATP "While you perform an attack, you **must** choose a defender at the closest valid attack range." It then causes an error and the game freezes.

In the screenshot, Zari Bangel is attacking Maarek Stele - but ATP wants Zari to target Saber Sq. Ace #4. Which I think is what's causing the crash.

It's happened to me twice, flying against the same AI list. Both times it was on Zari Bangel.

Hope that helps. Thanks for the game - love it.

**Comment by Sandrem** [comment] 2021-06-18 12:31
Duplicate of https://github.com/Sandrem/FlyCasual/issues/3115

**Closed by Sandrem** 2021-06-18 12:31 UTC
