### ISSUE TITLE
Seismic Charges Not Working in Android

### ISSUE THREAD

**Issue by hoarybat** [Sandrem/FlyCasual#1770] opened 2019-04-07 20:02 UTC
This is an issue with 0.8.0 in Android (on a Kindle Fire).  When the activation phase ends and the seismic charge detonated, I’m unable to select an obstacle to detonate. The obstacle flashes red with the seismic charge, but tapping it to select it does nothing. I end up having to tap “Skip” to continue, and the charge detonated without affecting the obstacle. This isn’t an issue in the 0.8.0 Mac build; only the Android version as far as I can tell.

**Comment by Sandrem** [comment] 2019-04-07 22:54
Duplicate of #1526 
As a workaround, use "controls: mouse" to select an obstacle.

**Closed by Sandrem** 2019-04-07 22:54 UTC
