### ISSUE TITLE
Sunny Bounder ability crashes game

### ISSUE THREAD

**Issue by AntipodeanOrk** [Sandrem/FlyCasual#2589] opened 2020-04-04 20:13 UTC
Several times now the game has locked up and the code screen has appeared when using Sunny's ability.

![image](https://user-images.githubusercontent.com/36247564/78460483-784b5980-7704-11ea-9d79-d32e5282d72c.png)

**Comment by rune-b** [comment] 2020-04-13 19:19
Duplicate of #2547

**Closed by rune-b** 2020-04-13 19:19 UTC
