### ISSUE TITLE
Chancellor Palpatine

### ISSUE THREAD

**Issue by aderius** [Sandrem/FlyCasual#3137] opened 2021-02-06 21:59 UTC
This ability is assigning ion tokens instead of stress (enemy is Warden Squadron Pilot in this case, palp is on Zam Wesell).

**Comment by Sandrem** [comment] 2021-02-13 05:40
![изображение](https://user-images.githubusercontent.com/6347443/107842807-9e369580-6dce-11eb-845a-af6cba6d109b.png)
Cannot reproduce. I checked code - Stress token is assigned too.
Please, provide screenshots / replay. Maybe there was another effect from another card that assigned ion token.

**Closed** 2021-07-09 17:21 UTC
Labels: Cannot reproduce
