### ISSUE TITLE
shooting on a rock

### ISSUE THREAD

**Issue by SmokeParnell** [Sandrem/FlyCasual#2247] opened 2019-08-30 01:08 UTC
i am hitting a problem when i tractor a ship of a lower or same INITIATIVE on to a rock with the Shadowcastor title and the tractored ship still being able to shoot back

**Comment by bitsai** [comment] 2019-08-30 05:36
Duplicate of #2173, fix is already in development branch, will be resolved in next release.

**Closed by bitsai** 2019-08-30 05:36 UTC
