### ISSUE TITLE
Lightweight Frame Upgrade Missing

### ISSUE THREAD

**Issue by SuperDuperCC** [Sandrem/FlyCasual#676] opened 2018-02-28 23:10 UTC
Note - Please remove if this isn't applicable.

As title suggests, the Lightweight Frame modification is not available. 

I can imagine this is a fairly complicated mechanic, but Quickdraw users will appreciate it.

**Comment by Sandrem** [comment] 2018-02-28 23:13
Game is in development, not all content is ready.
LWF has high priority, but I cannot say when it will be ready.

Closed as not a bug.

**Closed by Sandrem** 2018-02-28 23:13 UTC
