### ISSUE TITLE
Garvin Dreis Focus Generation

### ISSUE THREAD

**Issue by Translerbc** [Sandrem/FlyCasual#2986] opened 2020-11-08 16:10 UTC
Focus Assignment for Garvin Dreis (x-wing or Arc-170) doesn't work, nothing can be selected and game has to be restarted.
![Screen Shot 2020-11-08 at 9 02 45 AM](https://user-images.githubusercontent.com/74147377/98470334-29860680-21a2-11eb-9485-072de56a16b3.png)

**Comment by rune-b** [comment] 2020-11-08 21:35
Duplicate of #2900

**Closed by rune-b** 2020-11-08 21:35 UTC
Labels: Duplicate
