### ISSUE TITLE
Ello Asty's pilot ability doesn't trigger

### ISSUE THREAD

**Issue by rkukuchka** [Sandrem/FlyCasual#1597] opened 2019-02-19 03:56 UTC
During planning stages, talon roll is displayed as white, but when actually executed it leaves Ello stressed

**Comment by rkukuchka** [comment] 2019-02-19 04:09
Hrmm, not 100% reproducible. Let me try to get repro steps

**Comment by Sandrem** [comment] 2019-02-22 16:49
Maybe bacause ability says "if you have 2 or fewer stress tokens, treat that maneuver as white.", but you have 3 stress tokens?

**Comment by bitsai** [comment] 2019-07-08 05:18
Re-tested this in latest development branch, still couldn't reproduce, closing for now.

**Closed by bitsai** 2019-07-08 05:18 UTC
Labels: Cannot reproduce
