### ISSUE TITLE
Can't deploy ships

### ISSUE THREAD

**Issue by bhfroh** [Sandrem/FlyCasual#278] opened 2017-10-14 18:32 UTC
Just set up a game where it's 3 T-70s vs a TIE Advance and 2 TIE interceptors. I am supposed to be placing my ships but it won't let me grab them to place them

**Comment by bhfroh** [comment] 2017-10-14 18:35
Update, I have tried several different times with different ships, none of them seem to work.

**Comment by Sandrem** [comment] 2017-10-14 18:37
Did problem appear when you tried to start first battle after launch of application, or after you played at lease one game before without quiting to desktop?

**Comment by bhfroh** [comment] 2017-10-14 18:38
I hadn't played a single game. I finally fixed it though. It seems it happens when you use a specific screen resolution.

**Comment by Sandrem** [comment] 2017-10-14 18:40
If you know steps how to reproduce this problem - inform me. I only once got same bug, and still don't know how to reproduce it.

**Comment by bhfroh** [comment] 2017-10-14 18:47
I just chose a different screen resolution. 1600x900 is the resolution that would not work.

**Comment by Sandrem** [comment] 2017-11-02 16:47
Cannot reproduce. Seems that fixed with another related bugs.

**Closed by Sandrem** 2017-11-02 16:47 UTC
Labels: bug

**Comment by bhfroh** [comment] 2017-11-02 16:48
First tried launching
