### ISSUE TITLE
Saw glitch

### ISSUE THREAD

**Issue by Cannibal-Soup** [Sandrem/FlyCasual#2879] opened 2020-08-21 03:03 UTC
Saw was shooting at O-66 when the red wall of text popped up. 
![Screenshot_20200820-200148_Fly Casual](https://user-images.githubusercontent.com/68479348/90847803-37a15500-e320-11ea-9635-5e2c227826ff.jpg)

**Comment by rune-b** [comment] 2020-08-29 19:10
This is another case of the Treacherous bug. Seems to be a popular upgrade these days. Closing this one

Duplicate of #2832

**Closed by rune-b** 2020-08-29 19:10 UTC
Labels: Duplicate
