### ISSUE TITLE
Firespray's. Red reinforce

### ISSUE THREAD

**Issue by enosjr123** [Sandrem/FlyCasual#2631] opened 2020-04-25 15:54 UTC
fireaprays take green reinforced action.  When it is red.

**Comment by rune-b** [comment] 2020-04-25 18:19
Human or AI player?

**Comment by enosjr123** [comment] 2020-04-25 18:57
AI player

**Comment by Sandrem** [comment] 2020-04-25 20:46
Closed as duplicate of https://github.com/Sandrem/FlyCasual/issues/2599

**Closed by Sandrem** 2020-04-25 20:46 UTC
