### ISSUE TITLE
0.5.0 SE - Crit - Wounded Pilot giving stress when moving

### ISSUE THREAD

**Issue by bcutlerGC** [Sandrem/FlyCasual#992] opened 2018-06-03 20:33 UTC
Issue seen while playing Rebel list and Luke Skywalker had the Wounded Pilot Crital Damage card assigned. Card wording: "After you perform an action roll an attack die, on a hit or a crit assign a stress token"

It appears when I perform a manoeuvre the roll is being made and I am being assigned a stress. Which prevents me from ever clearing the crit using an action.

I will dd more info If I manage to see this happening again

![image](https://user-images.githubusercontent.com/37866837/40890881-cdc34aa4-6774-11e8-8516-369049c54b4c.png)

**Comment by Azrapse** [comment] 2018-06-03 21:30
Duplicate of #977 .
Are you using 0.5.0 Hotfix 1 version of FlyCasual?

**Comment by Sandrem** [comment] 2018-06-12 20:04
Cannot reproduce in "0.5.0 Hotfix 1".
Closed.

**Closed by Sandrem** 2018-06-12 20:04 UTC
