### ISSUE TITLE
Error message in the squadrons builder

### ISSUE THREAD

**Issue by Trokinos** [Sandrem/FlyCasual#371] opened 2017-11-29 19:16 UTC
Hello,

On my first attempt with 0.3.0 , i ran into an error message when, after having given 2 Tie Fighters to the AI, i gave myself a X-Wing , with Luke as the pilot.
Then when i was moving the mouse toward the Empty Slot (i didn't yet clicked on it) to check how much the cost would climb with some of them, the following error happened while my mouse was hoovering above 
https://i.imgur.com/mdRxWi1.gif

**Comment by Sandrem** [comment] 2017-11-30 15:25
Seems this bug was caused by missing Internet connection while game was trying to get tooltip with image of card of Luke Skywalker.
Fixed, will be in next update.

**Closed by Sandrem** 2017-11-30 15:25 UTC
