### ISSUE TITLE
Squadron don't spawn when containing TA-175

### ISSUE THREAD

**Issue by Hratly** [Sandrem/FlyCasual#2196] opened 2019-08-17 19:51 UTC
When TA 175 is in the squad, nothing shows up when creating a new game. An error said : an error occured when creating the squadron Autosave(Player1).json. When I remove him, everything is fine.

**Comment by Hratly** [comment] 2019-08-18 01:45
The same thing happened with tv-94. Didin't try the other tactical relay

**Comment by bitsai** [comment] 2019-08-18 03:40
Duplicate of #2172, fix will be included in next release.

**Closed by bitsai** 2019-08-18 03:40 UTC
