### ISSUE TITLE
1.3 constantly bugs out

### ISSUE THREAD

**Issue by AntipodeanOrk** [Sandrem/FlyCasual#2812] opened 2020-07-11 20:06 UTC
literally every decision point brings up the error screen.

Also, bug report won't allow the attachment of the replay file as it is the wrong file type?

**Comment by Sandrem** [comment] 2020-07-13 22:22
Please, don't use gas clouds until release of new version.

Duplicate of https://github.com/Sandrem/FlyCasual/issues/2811

**Closed by Sandrem** 2020-07-13 22:22 UTC
