### ISSUE TITLE
Von Reg Movement created a crash

### ISSUE THREAD

**Issue by JoelSpringle** [Sandrem/FlyCasual#2666] opened 2020-05-23 14:17 UTC
My 5 kihraxz moved.  Rush and Kylo moved.  Tehn VR moved - and thigns crashed.

![image](https://user-images.githubusercontent.com/65818951/82732971-a994de80-9cde-11ea-8fcf-6d17a3905568.png)

**Comment by redmoose79** [comment] 2020-05-24 12:58
happening on mine too. it crashes when AI has to select a strain or deplete token to complete his ability.  in last version you could select for him. in this one the option to choose for him isnt there and you just get stuck.

**Comment by Sandrem** [comment] 2020-05-25 19:03
I close this as duplicate of similar issue: https://github.com/Sandrem/FlyCasual/issues/2677

**Closed by Sandrem** 2020-05-25 19:03 UTC
