### ISSUE TITLE
Weapons System Officer points wrong / Rose Tico

### ISSUE THREAD

**Issue by LeoTheWookiee** [Sandrem/FlyCasual#3029] opened 2020-12-02 15:21 UTC
Weapons System Officer should cost 7pts (not 1)
Also, please please fix Rose Tico crew so that she can remove an eyeball and not auto exclude a blank (for Heroic this matters)

Once again, thanks a lot for this amazing app!

**Comment by Sandrem** [comment] 2020-12-08 18:35
Thank you, cost of Weapons Systems Officer is fixed.
Rose Tico's change of "remove a die" is a duplicate of existing issue https://github.com/Sandrem/FlyCasual/issues/2953

**Closed by Sandrem** 2020-12-08 18:35 UTC
