### ISSUE TITLE
Ship left field and dont be destroyed

### ISSUE THREAD

**Issue by Thorinblack1** [Sandrem/FlyCasual#1732] opened 2019-04-02 13:31 UTC
Happened with My milleniun Falcon just now. It passed off the mat in a cuve but wasn't destroyed

**Comment by Sandrem** [comment] 2019-04-08 01:45
I cannot reproduce. When a ship leaves the battlefield, it can perform action (known bug), but then it is destroyed. Please, next time provide screenshot.

**Comment by Thorinblack1** [comment] 2019-04-08 13:34
ok

**Comment by DejaFu** [comment] 2019-04-21 13:53
Not sure if this is what you saw, but, per the rules, if the ship leaves the battlefield, but then re-enters from the same maneuver (for example, a turn maneuver while at a 45 degree angle from the side, as long as they finish the maneuver on the battlefield, it doesn't count as leaving the battlefield.

**Comment by Thorinblack1** [comment] 2019-04-21 14:08
> Not sure if this is what you saw, but, per the rules, if the ship leaves the battlefield, but then re-enters from the same maneuver (for example, a turn maneuver while at a 45 degree angle from the side, as long as they finish the maneuver on the battlefield, it doesn't count as leaving the battlefield.

Are you sure? I'll Check this because since I've remebered I was taught otherwise and  just checked the rulebook and did'nt find anything related. Was it told in a FAQ?

**Comment by Thorinblack1** [comment] 2019-04-21 14:20
Just checked.You are right.... thanks

**Comment by DejaFu** [comment] 2019-04-21 14:25
From the rules FAQ, page 11:
FLEE
A ship flees if any part of its base is outside the play area after it
executes a
maneuver. A ship that flees is removed from the game.
• While a ship moves, the ship does not flee if only the template is outside
the play area.
• Before a fleeing ship is removed from the game, the only effects it
resolves before being removed from the game are effects that trigger
when it flees.
• A ship cannot flee while resolving a boost, barrel roll, decloak, or SLAM.
• Partially executing a maneuver can cause a ship to

**Closed** 2019-04-21 14:26 UTC
Labels: Cannot reproduce, Ship destruction
