### ISSUE TITLE
Game hanging after engagement

### ISSUE THREAD

**Issue by starjoe4** [Sandrem/FlyCasual#3242] opened 2021-04-12 00:55 UTC
Several times recently the game has stopped after an engagement.   Attack occurs, effects take place, but then - nothing.  trying to pick an enemy ship gives the 'belongs to another player' warning.  it's as if the attack circled back to the step where you need to pick your own ship in that initiative round but no ship is available.

**Comment by starjoe4** [comment] 2021-04-12 17:42
here's a shot of it happening - right after shooting with Anakin.  requiring me to pick a friendly i6 but no way to pick anakin again (he'd already shot).  nothing else will respond in game, have to ESC to either restart or quit.

![image](https://user-images.githubusercontent.com/47924192/114437713-e850b300-9b94-11eb-887d-cb316258ffa8.png)

**Comment by Sandrem** [comment] 2021-05-08 15:04
Duplicate of https://github.com/Sandrem/FlyCasual/issues/3230

**Closed by Sandrem** 2021-05-08 15:04 UTC
