### ISSUE TITLE
Advanced Sensors + Linked Actions

### ISSUE THREAD

**Issue by Sigmundr7** [Sandrem/FlyCasual#1309] opened 2018-10-28 16:10 UTC
In the last few games Advanced sensors has been working with single actions. However, with my current setup with B-wings and advanced sensors they are unable to perform the barrel roll action that is a linked when the focus action is performed. It has been a consistent issue since th last patch and relatively easy to recreate.

**Comment by Sandrem** [comment] 2018-10-28 19:17
Text of "Advanced Sensors":

After you reveal your dial, you may perform 1 action.
If you do, you cannot perform another action during your activation.

Linked action is the another action, so it cannot be performed.
If there are any information in rules/FAQ that Advanced Sendors allows execution of lined action - please, inform me.

Issue is closed as "Not a bug", until new info is provided.

**Closed by Sandrem** 2018-10-28 19:17 UTC

**Comment by Sandrem** [comment] 2018-10-28 19:59
Previous version of Advances Sensors was based on old version of card (from TIE Reaper/Saw's Renegades), where text was "... skip your Perform Action step" instead.
