### ISSUE TITLE
Scurrg can make primary attack outside front arc

### ISSUE THREAD

**Issue by krumok** [Sandrem/FlyCasual#1263] opened 2018-10-13 21:26 UTC
If scurrg is equipped with turret e.g. ion turret, it can make primary attack from mobile arc left, right, rear

**Comment by Sandrem** [comment] 2018-10-23 16:08
Duplicate of https://github.com/Sandrem/FlyCasual/issues/1252

**Closed by Sandrem** 2018-10-23 16:08 UTC
