### ISSUE TITLE
Problem with the Child

### ISSUE THREAD

**Issue by WatcherSquadron** [Sandrem/FlyCasual#3350] opened 2021-09-16 20:51 UTC
When you defend with a ship equipped with the Child, it crashes the game, it can also start to give him additional force if you have no force to recover.

**Comment by achapin** [comment] 2021-11-26 14:49
This looks like a duplicate of https://github.com/Sandrem/FlyCasual/issues/3339

**Closed** 2021-12-24 16:41 UTC
