### ISSUE TITLE
Dash Rendar Countermeasures Crash Game

### ISSUE THREAD

**Issue by Bismarcksea** [Sandrem/FlyCasual#511] opened 2018-01-21 16:45 UTC
Here is the setup:  Two Tie Bombers use LRS to get two target locks.   
Next Turn,  Dash pops countermeasures and looses BOTH target locks.....and then game crashes.

-Thanks!

**Comment by Sandrem** [comment] 2018-02-19 16:59
Still cannot reproduce.
If you will get same problem again - please, make a screenshot of condole with red text.

**Comment by Bismarcksea** [comment] 2018-02-20 23:42
Screenshot of bug attached!
![dash error](https://user-images.githubusercontent.com/35663377/36455376-c49f7ac2-166d-11e8-951a-aa93cc756e84.JPG)

**Comment by Sandrem** [comment] 2018-02-21 22:01
Countermeasures are fixed in development branch.
Release of new version is planned on Friday.

**Closed by Sandrem** 2018-02-21 22:01 UTC
Labels: Bug, Cannot reproduce
