### ISSUE TITLE
bug treacherous

### ISSUE THREAD

**Issue by Immelman51** [Sandrem/FlyCasual#2832] opened 2020-07-26 06:32 UTC
Hi. Here's a report. thanks as usual

[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4977206/LastReplay.zip)
![Annotation 2020-07-26 083212](https://user-images.githubusercontent.com/31988939/88473116-9094ed80-cf1a-11ea-813f-db18639f0fad.png)

**Comment by rune-b** [comment] 2020-08-24 20:46
Confirmed. Got the same error with two A-Wings agains Sun Fac with treacherous

![image](https://user-images.githubusercontent.com/11047987/91094819-a56cba00-e65b-11ea-80ab-b7841d569d49.png)

**Comment by rune-b** [comment] 2020-08-24 21:06
The bug is caused in the IsDiceModificationAvailable() method because the Source property is null. I tried setting it to HostUpgrade and then it worked and I could use treacherous. But afterwards when resolving the hits of the attack the game gets stuck (see error text at the bottom)

![image](https://user-images.githubusercontent.com/11047987/91096325-29c03c80-e65e-11ea-8d69-9ffc05103fa3.png)

**Comment by rune-b** [comment] 2020-08-25 20:15
related to #2706

**Comment by Sandrem** [comment] 2021-01-22 01:17
Fixed

**Closed by Sandrem** 2021-01-22 01:17 UTC
Labels: Bug
