### ISSUE TITLE
Any time I try to play a game it does this:

### ISSUE THREAD

**Issue by bhfroh** [Sandrem/FlyCasual#382] opened 2017-12-02 19:38 UTC
![image](https://user-images.githubusercontent.com/32801256/33519130-1c9c831a-d766-11e7-9a4f-139ad6ca8b79.png)

**Comment by Sandrem** [comment] 2017-12-16 01:05
I cannot reproduce this bug.
I can provide you a test-build that can give more information about this bug.
Will you have time to test this again?

**Comment by Sandrem** [comment] 2018-01-10 20:09
Seems that it is fixed now. Please, report this bug again if it will appear in 0.4.0.

**Closed by Sandrem** 2018-01-10 20:09 UTC
Labels: Bug, Cannot reproduce
