### ISSUE TITLE
Crash after AI Boba ran over asteroid

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1504] opened 2019-02-05 16:09 UTC
0.7.2 android 

![screenshot_20190205-170712](https://user-images.githubusercontent.com/11047987/52286518-9edafc80-2968-11e9-8dca-550c1287192c.png)

**Comment by Sandrem** [comment] 2019-06-14 02:53
No similar bug reports from another users. I cannot reproduce this bug too.
(Maybe was fixed by another changes?)
Closed.

**Closed by Sandrem** 2019-06-14 02:53 UTC
Labels: Cannot reproduce
