### ISSUE TITLE
AI stuff

### ISSUE THREAD

**Issue by OnlyOneD** [Sandrem/FlyCasual#548] opened 2018-01-28 01:03 UTC
1-Currently white manoeuvres clear stress... afaik by x-w tmg rules only greens do. Also most red manoeuvres don't give stress atm... seems only K-manouvres do that.

2-when equipped with certain upgrades, like eg r2d2 droid, AI should try to do green manouvres when below max shield (if it's likely it won't get any dmg orso .. seems it hardly used .. also implament t5-p9 plz).

3-3rd: gunner, or pretty much any of the 'can shoot again' features ... it shows/gives a msg that a certain aircraft can shoot again, but AI never does it.

4-With AI, planes equipped with Advanced Optics seem to choose focus alot even though it already has a focus and can only have 1.

5-AI craft tend to 'choose' to do a manoeuvre alot which surely get's them off-board next turn, please make them see at least 1 turn a head to see if they'd be able to keep onboard .. (maybe make it an option to see asteroids next turn too to make it more 'human' but still allow Aturi cluster AI)

Most extra utility/equipment functions don't seem to be used with AI (eg bb8) ... imo, if you equip something if it has a use of 2 or more targets (evading or getting closer to or whatever) it should be used (thinking bombs etc here)/or at least is capable of doing more dmg than say normal attack, which most do .. why else bring missiles/torpedos etc?  ... but imo, in any case ornaments like missiles etc should be used before anything else if it is capable of more dmg (no use bringing them if you're dead before using the points)

In general, I think most upgrade cards should have priority above anything else ... no use 'buying' upgrades if you'll get shot down before using them ...

**Comment by Sandrem** [comment] 2018-01-28 01:39
1) HotAC AI rules: AI ships don't assign stress after red maneuver - they just skip action instead. If AI ship is assigned stress by ability - they can remove it as action.
2) I don't have enough time to make complex AI for each upgrade. If you or another developer want to code this behavior - welcome! =) R5-P9 is already in development, as I remember.
3) At the moment AI cannot handle abilities that require to select ship that meets specific criteria - so second attacks are skipped by AI. I plan to improve this part in nearest updates.
4) see #2
5) Predictions by two turn ahead - in plans, but this is complex feature.

Creation of AI is COMPLEX (I really want to use even larger letters for this word).
I use basic rules of HotAC AI (tables of maneuvers, swerve) and calculate priority of actions / order of dice modifications. There a lot of ways to improve AI, but this requires a lot of my time (that I spend instead of paid job or rest).

Issue closed as not a bug.

**Closed by Sandrem** 2018-01-28 01:39 UTC
