### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GyoMan** [Sandrem/FlyCasual#2995] opened 2020-11-10 22:47 UTC
Win10

Edition First selected

New game - versus AI - The Rebel Alliance - New Ship

![bug](https://user-images.githubusercontent.com/16439531/98742519-42b3d080-23b7-11eb-83c7-bcc68fc23ed0.png)

**Comment by rune-b** [comment] 2020-11-11 07:59
Hi
This has already been reported and a fix is on the way. So I will close this one

Duplicate of #2990

**Closed by rune-b** 2020-11-11 07:59 UTC
