### ISSUE TITLE
0.4.2 TIE/D AI ships not taking follow up shot

### ISSUE THREAD

**Issue by Kelbesq** [Sandrem/FlyCasual#673] opened 2018-02-28 18:00 UTC
When playing against a TIE Defender with the TIE/D title, the AI is not using it's follow up primary attack after it's cannon attack.   The UI is showing a message indicating that the follow up attack can occur, but it is not being performed.

I have only personally seen this with Colonel Vessery and an Ion Cannon, but I have not done extensive testing.

**Comment by Sandrem** [comment] 2018-02-28 23:04
This is for all "additional attack" abilities, will be improved later.

**Comment by Sandrem** [comment] 2018-03-31 23:00
I close this issue as not a bug. Support of second attack will be added for AI in one of next updates.

**Closed by Sandrem** 2018-03-31 23:00 UTC
