### ISSUE TITLE
5th Brother w/ Homing Missiles Vs Alexandr Kallus w/ Reinforce issue?

### ISSUE THREAD

**Issue by wowiebowie** [Sandrem/FlyCasual#2761] opened 2020-06-18 12:24 UTC
![image](https://user-images.githubusercontent.com/67105278/85019372-9f8fbf80-b166-11ea-9242-3594cc8f1b10.png)

**Comment by Sandrem** [comment] 2020-06-19 20:26
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2668

**Closed by Sandrem** 2020-06-19 20:26 UTC
