### ISSUE TITLE
Game won't start after squad build

### ISSUE THREAD

**Issue by dankwc2000** [Sandrem/FlyCasual#276] opened 2017-10-13 13:54 UTC
The game won't start after building the lists.  It thinks one of the squads exceeds the 100pt limit.
![image](https://user-images.githubusercontent.com/14838021/31549550-760f485e-b026-11e7-9459-12c92e593201.png)

**Comment by Sandrem** [comment] 2017-10-13 14:12
I needs steps to reproduce (full lists that cause this problem).
Also, pay attention if you removed/copied any ships - maybe problem appears only after these actions (for example, ship was removed form list, but it's cost is still present)

**Comment by dankwc2000** [comment] 2017-10-13 14:29
I added the YT-1300 and selected Han and added the upgrades in the screenshot, followed by A Wing Tycho and his upgrades.  Then I moved onto changing the otherside to Rebels and selecting Horton and added the upgrades.  Then one gold squadron was added with the upgrades, then I copied it over.  The second gold squadron was missing the proximity mine and that was added.  Nothing was removed during the steps.

**Comment by Lord-Eye** [comment] 2017-10-14 00:58
Excellent work!

TLT wouldn’t fire on the Ghost. Message said out of arc, and gave no option for secondary weapon.  This was intermittent, as sometimes it would allow me to use the TLT.

Sent from Mail for Windows 10

**Comment by Sandrem** [comment] 2017-10-14 13:30
Found a way to reproduce it - bug is caused by upgrades that grant additional slots.
Will be fixed in hotfix in few days.

**Comment by Sandrem** [comment] 2017-10-23 14:46
Bomb Loadout upgrade is fixed.

**Closed by Sandrem** 2017-10-23 14:46 UTC
Labels: bug
