### ISSUE TITLE
Ello t-roll

### ISSUE THREAD

**Issue by Vinter144** [Sandrem/FlyCasual#2652] opened 2020-05-03 23:04 UTC
I had multiple issues with the game crashing on android when performing Ellos white t-roll.

**Comment by Sandrem** [comment] 2020-05-14 17:42
Cannot reproduce.

Please, next time provide screenshot, or find steps that allow to reproduce bug with 100% chance.

**Comment by Vinter144** [comment] 2020-05-14 17:52
Yep, sorry. I realized I should have done that.

Actually the problem is gone, it have not occured since I made the post.
Before that it happened 5+ times in a row.

Thanks for getting back to me and for all the work you put in. It is much
appriciated.

Mikael

Den tors 14 maj 2020 19:42Sandrem <notifications@github.com> skrev:

**Comment by Sandrem** [comment] 2020-05-14 18:05
I will close this issue. Please, open it again, with additional info, if you will enounter same problem again.

**Closed by Sandrem** 2020-05-14 18:05 UTC
Labels: Cannot reproduce
