### ISSUE TITLE
Double Decloak bug/Triggers Order Window

### ISSUE THREAD

**Issue by Liquidlogic1** [Sandrem/FlyCasual#190] opened 2017-08-31 22:21 UTC
https://imgur.com/gallery/3XkTa

This window popped up: "Activation Phase: triggers order" after a player controlled Phantom was ionized (the round after being ionized).  This enabled multiple decloaks to happen, each with a "do you want to decloak?" window. This affected both the ionized and non-ionized Phantom. (I was playing Whisper/Shadow Squadron Phantoms and Soontir Fel).  I'm not sure if the ionization caused it or not. I had several rounds successfully cloaking and decloaking before this happened.

**Comment by Sandrem** [comment] 2017-09-02 14:42
Cannot reproduce.
Will be fixed later, when steps to reproduce will be found.

**Comment by Liquidlogic1** [comment] 2017-09-05 00:20
I can clarify what causes this bug - It only happens when two phantoms are in play and both are cloaked at the same time.  If only one is cloaked, it functions normally.

To reproduce: fly any two Tie Phantoms. Select cloak action for both. On the next turn, the bug will occur when it asks you to decloak.

**Comment by Sandrem** [comment] 2018-04-04 00:47
Cloak feature will be rewritten n 0.5.0 - old bugs are not actual anymore.

**Closed by Sandrem** 2018-04-04 00:47 UTC
Labels: Bug
