### ISSUE TITLE
Tractor Beam ability from Foreman Proach hangs after barrel rolling enemy

### ISSUE THREAD

**Issue by lars30** [Sandrem/FlyCasual#3390] opened 2021-11-12 17:46 UTC
Not sure if this is a duplicate.

After I barrel roll the enemy with Foreman Proach's Mining X-Wing bulls eye ability, the game does not allow me to continue. It's supposed to assign a disarm toke to Foreman Proach and then finish the engagement phase for that ship.
[LastReplay.replay.txt](https://github.com/Sandrem/FlyCasual/files/7529448/LastReplay.replay.txt)

**Comment by ersk** [comment] 2021-11-14 14:33
The game fails to show the Skip or Next button, therefore not allowing the user to continue. I managed to reproduce this when the enemy ship is barrel rolled onto an asteroid. Not sure about other obstacles or the boost forward. It works when no obstacles are involved however.

**Comment by ersk** [comment] 2021-11-14 14:50
Duplicate of #2957

**Comment by Sandrem** [comment] 2021-11-15 15:44
Closed as duplicate

**Closed by Sandrem** 2021-11-15 15:44 UTC
