### ISSUE TITLE
Fifth Brother/Homing Missiles bug?

### ISSUE THREAD

**Issue by icampbellatk** [Sandrem/FlyCasual#2762] opened 2020-06-20 04:52 UTC
![image](https://user-images.githubusercontent.com/22477850/85192330-1bd1f200-b290-11ea-800d-bc9dfded80f3.png)

All my ships (infernos 1-3, duchess, and finally Fifth Brother) fired on a Scurrg - Fifth Brother and his ability (+ homing missiles) did the last 2 damage, but adding the crit popped this up. Not sure which part is breaking, but here you go!

**Comment by Sandrem** [comment] 2020-06-24 04:02
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2668

**Closed by Sandrem** 2020-06-24 04:02 UTC
