### ISSUE TITLE
Everytime Berwer Kret is shot at the game crashes. Happened 4x now

### ISSUE THREAD

**Issue by Armytuba** [Sandrem/FlyCasual#2924] opened 2020-09-18 09:46 UTC
![image](https://user-images.githubusercontent.com/71455776/93583722-448e8400-f972-11ea-8d90-96881c9953f8.png)

**Comment by rune-b** [comment] 2020-09-21 21:17
Hi. This is a bug with Treacherous that has already been reported, so I'm closing this one.

Duplicate of #2832

**Closed by rune-b** 2020-09-21 21:17 UTC
