### ISSUE TITLE
Leia (rebel crew)

### ISSUE THREAD

**Issue by carlosaredo** [Sandrem/FlyCasual#2263] opened 2019-09-04 09:04 UTC
If Leia (rebel crew) is in your list, any stressed ship can do actions even if Leia is not activated in this turn

**Comment by bitsai** [comment] 2019-09-04 17:17
Tested using Cassian (in a U-wing, with Leia crew equipped) and Braylen, was not able to reproduce.  I dialed in a red stop for Cassian and a 2 k-turn for Braylen, skipped Leia's activation, and did not get actions for either Cassian or Braylen.

Can you share screenshots and the steps needed to reproduce the situation?

**Comment by bitsai** [comment] 2019-09-06 05:29
I'm going to close this for now, but if you see this again, please feel free to open (ideally with the additional info mentioned above).  Thanks!

**Closed by bitsai** 2019-09-06 05:29 UTC
Labels: Cannot reproduce
