### ISSUE TITLE
Error in movement phasw

### ISSUE THREAD

**Issue by amoyag** [Sandrem/FlyCasual#2778] opened 2020-06-26 12:39 UTC
Error jus after the AI completed its movement
[LastReplay.replay.zip](https://github.com/Sandrem/FlyCasual/files/4836934/LastReplay.replay.zip)

**Comment by Sandrem** [comment] 2020-06-26 20:01
Error is caused by AI-controlled TIE/ba
Fixed in dev-branch

**Closed by Sandrem** 2020-06-26 20:01 UTC
