### ISSUE TITLE
Vader (second edition, pilot) can't take other actions after failed TL action

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2147] opened 2019-08-01 10:09 UTC
After trying to do a Target Lock action (and failing) he doesn't get the option to spend a force to do another action.

**Comment by rune-b** [comment] 2019-08-01 14:32
Should he be able to? If the action failed he has not performed an action as far as I can see...

**Comment by bitsai** [comment] 2019-08-01 16:01
According to this thread in the FFG X-wing rules forum (https://community.fantasyflightgames.com/topic/292066-darth-vader-and-failed-actions/), this definition of failing from pg. 11 of the rules reference (specifically the bolded section) means that Vader does not get to use his ability after failing an action:

**FAIL**
Some effects can fail, which means the effect did not resolve as intended and
instead is resolved in a default way.
• A ship can fail when it barrel rolls, boosts, coordinates, decloaks, deploys,
jams, locks, or SLAMs.
• **An effect that fails does not trigger any effects that would occur after a
ship resolves that effect.**
• If an action fails, the player does not choose a different action to perform
and cannot choose to resolve the effect in a different way.
• If an action fails, since the action was not completed, that ship cannot
perform a linked action.
• After a red action fails, the ship gains a stress token.

**Closed by bitsai** 2019-08-01 16:01 UTC
