### ISSUE TITLE
[9.1.1] Trigger resolution crashes game

### ISSUE THREAD

**Issue by NerdimusPrime** [Sandrem/FlyCasual#2008] opened 2019-07-02 16:04 UTC
After a proton bomb went off, destroying a fang fighter, this crash occurred.
<img width="2523" alt="Trigger_Error" src="https://user-images.githubusercontent.com/1558951/60528040-8aa1ee00-9cc1-11e9-8a0f-bc9c1e9381e8.png">

**Comment by Sandrem** [comment] 2019-07-02 16:19
Thank you for screenshot. Seems that this bug is duplicate of bug, caused by Sabine Wren
https://github.com/Sandrem/FlyCasual/issues/1963

**Closed by Sandrem** 2019-07-02 16:19 UTC
