### ISSUE TITLE
Weird bumping issue where ships actually overlapped and snap shot

### ISSUE THREAD

**Issue by stavrjim** [Sandrem/FlyCasual#2902] opened 2020-09-03 09:27 UTC
Snap shot is costed incorrectly (9 points for medium should be 8). Also, these IGs overlapped
![image](https://user-images.githubusercontent.com/26796723/92097480-0751c000-edd0-11ea-8032-680a762879e7.png)

**Comment by rune-b** [comment] 2020-09-08 16:00
Snap shot cost will be fixed in the next release

This overlap is strange though. Did it happen as part of their regular movement? Do you remember which maneuver the overlapping ship did?

**Comment by Symbiode** [comment] 2020-09-16 05:58
I've been seeing a lot of overlaps with the recent version
, where ships that should bump just pass through others. In this case, Dengar was doing a 1 straight and should have bumped, but isntead passed through and landed on this nantex:
![Overlap](https://user-images.githubusercontent.com/9201363/93297800-081b2680-f7c0-11ea-8f59-059255820481.PNG)

**Comment by Akrythael** [comment] 2020-10-31 12:43
I can confirm seing this happening from time to time since version 1.4 or 1.5.

3 bank

![unknown](https://user-images.githubusercontent.com/47178393/97779520-dd720b00-1b7e-11eb-8d47-9daa63d70fc8.png)

5 straight

![unknown (1)](https://user-images.githubusercontent.com/47178393/97779550-0abeb900-1b7f-11eb-832e-7d2393c76614.png)

**Comment by Sandrem** [comment] 2020-12-08 16:52
Some fixes are done. If this bug will be present in 1.8+, please inform me.

**Closed by Sandrem** 2020-12-08 16:52 UTC

**Comment by Akrythael** [comment] 2020-12-08 16:55
> Some fixes are done. If this bug will be present in 1.8+, please inform me.

Sure! Will do ;)
