### ISSUE TITLE
Treacherous causing crash when ship with upgrade is defending

### ISSUE THREAD

**Issue by subhedgehog** [Sandrem/FlyCasual#2871] opened 2020-08-14 19:58 UTC
Happened on the first shot targeting a ship with treacherous.

![flycasual-treacherous-crash](https://user-images.githubusercontent.com/3179208/90287987-ce0bdd00-de2d-11ea-987a-714a67d32c7b.png)
[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/5076918/LastReplay.zip)

**Comment by rune-b** [comment] 2020-08-25 20:15
Thanks for reporting. I'm closing this because it is a duplicate of #2832

**Closed by rune-b** 2020-08-25 20:15 UTC
