### ISSUE TITLE
Predator not triggering 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1677] opened 2019-03-18 07:56 UTC

**Comment by rune-b** [comment] 2019-03-18 07:57
![Screenshot_20190318-014658](https://user-images.githubusercontent.com/11047987/54514964-c8ba1280-495b-11e9-80a1-2297927d0185.png)

**Comment by Sandrem** [comment] 2019-03-24 19:17
Cannot reproduce. Maybe, some additional steps are needed.
![image](https://user-images.githubusercontent.com/6347443/54884476-41e4c880-4e7a-11e9-8fc5-28a0e7ff2dae.png)

**Comment by bitsai** [comment] 2019-07-12 11:21
Tried again to reproduce in latest development branch, no luck so far, closing for now.

**Closed by bitsai** 2019-07-12 11:21 UTC
Labels: Cannot reproduce

**Comment by Sandrem** [comment] 2019-07-12 11:36
As I see, this bug is part of global problem that sometimes ship is shown as not in arc, when there is a ship between attacker and defender. I will try to investigate this today.
