### ISSUE TITLE
Error in combat phase (Biggs Darklighter?)

### ISSUE THREAD

**Issue by elsapo70** [Sandrem/FlyCasual#2776] opened 2020-06-25 09:19 UTC
The rror message appears as soon as the opponent attacks.
[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4830275/LastReplay.zip)

**Comment by Sandrem** [comment] 2020-06-26 20:28
First Edition, "Partisan Title" mod must be turned on.

**Comment by Sandrem** [comment] 2020-06-27 01:03
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2413

**Closed by Sandrem** 2020-06-27 01:03 UTC
Labels: First Edition
