### ISSUE TITLE
Fifth brother with concussion missles 

### ISSUE THREAD

**Issue by barfolomew4** [Sandrem/FlyCasual#2719] opened 2020-06-04 14:39 UTC
After spending the 2 force to trigger an extra crit the game crashes. 
![Screenshot_20200604-103018_Fly Casual](https://user-images.githubusercontent.com/50247192/83770926-a9d29980-a64f-11ea-86e7-12086f727de1.jpg)

**Comment by PsyonicReign** [comment] 2020-06-06 17:22
same result with Homing Missiles

**Comment by ootinni** [comment] 2020-06-07 01:12
got the same thing with homing missiles
![Screenshot_20200607-021151](https://user-images.githubusercontent.com/52763171/83957958-5be2af00-a864-11ea-8eb5-0aae399fe7df.png)

**Comment by donfonz** [comment] 2020-06-09 01:43
Ah yes this is the same thing I reported so can delete my ticket

**Comment by Sandrem** [comment] 2020-06-19 20:08
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2668

**Closed by Sandrem** 2020-06-19 20:08 UTC
