### ISSUE TITLE
Token is displayed incorrectly

### ISSUE THREAD

**Issue by djeknemesis2012** [Sandrem/FlyCasual#487] opened 2018-01-20 00:03 UTC
Build: 0.4.0

Steps:

1. Choose a ship with one upgrade. 
2. In first turn choose a focus.

Actual result: token is displayed out of place.
Expected result: token is displayed in place.

![1](https://user-images.githubusercontent.com/34982133/35177149-70578ede-fd8e-11e7-86cc-942b84b569b7.jpg)

**Comment by rats3g** [comment] 2018-02-09 21:35
I attempted to replicate this issue with the current development version using the same setup. 

Following the steps:

1. Choose a ship with one upgrade (Syndicate Thug Y-Wing, Ion Cannon Turret)
2. Choose a focus on first turn

I was unable to reproduce the issue with the focus token showing as in the expected image above.

**Comment by Sandrem** [comment] 2018-02-09 21:52
Additional requrements: this is ship of second player and this is first activation in the activation phase.

**Comment by Sandrem** [comment] 2018-05-01 06:02
Fixed by update of Unity to v2018.2.0b2

**Closed by Sandrem** 2018-05-01 06:02 UTC
Labels: Bug
