### ISSUE TITLE
ships that are tractored onto rocks do not roll for damage

### ISSUE THREAD

**Issue by boredompwndu** [Sandrem/FlyCasual#2624] opened 2020-04-25 02:41 UTC
![image](https://user-images.githubusercontent.com/8730661/80269295-72e68c80-867c-11ea-94a1-abaadcc29532.png)

In this scenario, Obi Wan was tractored by Zuvio, moving him onto the rock. Obi Wan Rotated as he is allowed by the new tractor rules, but he did not move roll for moving onto the rock.

Occured in 0.9.8 and 1.0 hotfix

1.0 hotfix looks super nice btw. Appreciate the animation speed slider affecting more things

**Comment by rune-b** [comment] 2020-04-25 21:41
Was he tractored using the straight forward template? Probably same bug as #2314

**Comment by boredompwndu** [comment] 2020-04-26 01:53
yes

**Comment by Sandrem** [comment] 2020-06-27 01:00
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2314

**Closed by Sandrem** 2020-06-27 01:00 UTC
Labels: Bug
