### ISSUE TITLE
Jake's ability not working 

### ISSUE THREAD

**Issue by Vipcard3** [Sandrem/FlyCasual#1448] opened 2019-01-16 22:41 UTC
When using Jake Farrell his ability isn't letting other ships focus.  It also isn't activating on the red boost when using barrel->(focus) boost.

**Comment by rune-b** [comment] 2019-01-17 21:20
Duplicate of #1350

**Comment by Sandrem** [comment] 2019-01-31 19:42
Closed as duplicate

**Closed by Sandrem** 2019-01-31 19:42 UTC
Labels: Bug, duplicate
