### ISSUE TITLE
Crash on enacting Thanisson ability on Jake Farrell at end of engagement following Phasma stress application

### ISSUE THREAD

**Issue by gl74** [Sandrem/FlyCasual#2873] opened 2020-08-16 20:42 UTC
Repeatable crash.

At end of engagement phase Thanisson ability triggers correctly but when JF is barrel-rolled game crashes. Screenshot + log attached.

Thanks for all the good work
![Thanisson ability crash](https://user-images.githubusercontent.com/69769907/90343509-c48a9c80-e008-11ea-99cb-3cd01d827f13.png)

[LastReplay.txt](https://github.com/Sandrem/FlyCasual/files/5081345/LastReplay.txt)

**Comment by rune-b** [comment] 2020-08-26 19:35
duplicate of #2883

**Closed by rune-b** 2020-08-26 19:35 UTC
