### ISSUE TITLE
Unable to Skip usage of Countermeasures/Glitterstim

### ISSUE THREAD

**Issue by rats3g** [Sandrem/FlyCasual#616] opened 2018-02-13 02:03 UTC
Steps to reproduce:

1. Setup game with Asajj (2x Glitterstim, Countermeasures)
2. Complete a maneuver with Asajj
3. Select an action
4. Attempt to Skip the usage of Glitterstim/Countermeasures before beginning Combat

Result:
Unable to Skip the usage of Glitterstim/Countermeasures and begin combat. Instead each option must be selected and specifically declined via a Yes/No selection.

![asajj bug](https://user-images.githubusercontent.com/4007006/36129980-03d40dac-1038-11e8-8328-6b36a805eb28.png)

**Comment by Sandrem** [comment] 2018-02-13 02:23
All these three triggers are result of cards that have "At the begining of combat phase" abilities.
So in the begining of combat phase game asks player: "You have 3 abilities that want to do something - select order of them".
And player chooses order of triggers, and for each triggered ability, when ability asks for activation of effect, player can answer "No, I don't want to use ability".

So all this is correct behavior of trigger-based abilities. You can see "Magic the Gathering Online" as example.

Player can skip usage of Glitterstim/Countermeasures effect, but cannot skip triggers that are called by rules of the game.

If you have ideas how to handle such situations better - I am ready to discuss in #programming channel is Slack.

This issue is closed as not a bug.

**Closed by Sandrem** 2018-02-13 02:23 UTC
