### ISSUE TITLE
Thane 

### ISSUE THREAD

**Issue by egudmunson1977** [Sandrem/FlyCasual#2721] opened 2020-06-04 19:37 UTC
![image](https://user-images.githubusercontent.com/66441012/83802670-ca5f1b80-a670-11ea-8bb6-924590a1d04f.png)
I was using thane and it crashed

**Comment by Sandrem** [comment] 2020-06-27 00:22
Thank you.

Duplicate of https://github.com/Sandrem/FlyCasual/issues/2764

**Closed by Sandrem** 2020-06-27 00:22 UTC
