### ISSUE TITLE
Better AI versus TLT (not quite an issue, but don't where to post)

### ISSUE THREAD

**Issue by qasur** [Sandrem/FlyCasual#804] opened 2018-04-11 19:19 UTC
I played a list using Twin Laser Turrets (TLT) and Tractor Beam (TB) against some YWings (with only 1 Agility, therefore only 1 Defense die) and I noticed throughout the game that the AI would spend their Focus token on defense (as I was shooting first) against either TLT/TB when I landed 2 or more hits against them that the ship could not actually stop.

Both TLT & TB (and Jam Cannon, Fletchette Cannon, and other similar weapons) only deal maximum of 1 non-crit damage, so you if you are not able to roll enough to defend, there is no need to waste a token changing a die result.

**Comment by Sandrem** [comment] 2018-04-29 02:10
Closed as duplicate of https://github.com/Sandrem/FlyCasual/issues/785

**Closed by Sandrem** 2018-04-29 02:10 UTC
