### ISSUE TITLE
Zeb crew not allowing attacks at r0

### ISSUE THREAD

**Issue by YellowJacketPym** [Sandrem/FlyCasual#3169] opened 2021-02-17 04:18 UTC
![image](https://user-images.githubusercontent.com/61330588/108155644-438e8980-70ad-11eb-9dd8-f26f38fdcfa5.png)

**Comment by ClarenceR89** [comment] 2021-03-12 08:01
Same issues as #3109 

Zeb Crew does not allow range 0 attacks

**Comment by Sandrem** [comment] 2021-05-08 14:01
Duplicate of https://github.com/Sandrem/FlyCasual/issues/3109

**Closed by Sandrem** 2021-05-08 14:01 UTC
