### ISSUE TITLE
Anakin Skywalker was able to barrel roll on a gas cloud

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2189] opened 2019-08-16 07:43 UTC
With Anakin I first used a force to do a boost left and then as his regular action, I was able to select a barrel roll (left forward) which clipped the rock, but was still allowed to perform.

**Comment by bitsai** [comment] 2019-08-16 21:36
Tried to reproduce using Anakin and the same steps (boost left w/ Fine-Tuned Controls, then barrel roll left forward towards an obstacle), but was not able to reproduce the issue.  Also tried with both rocks and gas clouds.

Is this happening regularly for you, or only sometimes?  When it happens, does the ship overlap the obstacle by a lot or just a little (like the screenshot in #2174)?

**Comment by pinosante** [comment] 2019-08-17 20:57
Hi, it happens very rarely. It happened twice. Once with Anakin, and once when an enemy ship did a maneuver. In both cases, it looked like the screenshot #2174: it would clip the asteroid just a mm, but very visible that it did clip. The asteroid with which this happened was the long straight gas cloud and it clipped the bottom left corner. Hope this helps.

**Comment by bitsai** [comment] 2019-08-18 05:13
I'm not 100% certain, but it seems like this and #2174 may both be caused by small inaccuracies in obstacle overlap checking.

**Comment by rune-b** [comment] 2019-08-19 20:05
Likely related to #1634

**Comment by pinosante** [comment] 2019-08-22 18:02
More proof of similar behaviour. The AI just did a k-turn on the rock, this shows that internally the AI thinks that it fits.

https://imgur.com/a/gEiff3p

**Comment by bitsai** [comment] 2019-08-22 20:29
At this point I'm pretty sure this and #2174 share the same root cause, going to go ahead and close this one to keep the issues list under control.

**Closed by bitsai** 2019-08-22 20:29 UTC
Labels: Bug
