### ISSUE TITLE
Treacherous causing crash.

### ISSUE THREAD

**Issue by baronklutz** [Sandrem/FlyCasual#2899] opened 2020-09-01 13:37 UTC
When an attack is measured through a ship onto one with treacherous the game crashes. Will post later with screenshot.

**Comment by baronklutz** [comment] 2020-09-01 14:27
![image](https://user-images.githubusercontent.com/52109920/91864032-aeffae80-ec67-11ea-885c-5799d8a999d0.png)

**Comment by Immelman51** [comment] 2020-09-01 19:11
It happened for me to.

**Comment by rune-b** [comment] 2020-09-21 21:16
This has already been reported, so I'm closing this one.

Duplicate of #2832

**Closed by rune-b** 2020-09-21 21:16 UTC
