### ISSUE TITLE
Phasma.  And Petty Officer Thanisson

### ISSUE THREAD

**Issue by enosjr123** [Sandrem/FlyCasual#2746] opened 2020-06-12 05:58 UTC
the game doesn't give out all stress to ships in range one with Cpt. Phasma.   And Thanissons tractor makes the game crash.   Time of Thanisson is off as well.    Not sure if he can use his ability at the end of engagement.

**Comment by rune-b** [comment] 2020-08-26 19:35
duplicate of #2883

**Closed by rune-b** 2020-08-26 19:35 UTC
