### ISSUE TITLE
crashes when Nora Wexley (BTL-A4) engages

### ISSUE THREAD

**Issue by pakirby1** [Sandrem/FlyCasual#1604] opened 2019-02-22 12:27 UTC
Ran into this three separate times after creating a 200 point list

<img width="1273" alt="screen shot 2019-02-22 at 4 22 40 am" src="https://user-images.githubusercontent.com/5995377/53242577-ff04ba80-3659-11e9-859c-f44ba1085e66.png">

**Comment by pakirby1** [comment] 2019-02-22 12:55
Or sometimes when Vader defends.  `NullReferenceException`

**Comment by bitsai** [comment] 2019-07-08 05:26
Re-tested this in latest development branch by flying Vader against AI Norra Y-wing (with the same loadout as in the screenshot), couldn't reproduce any crashes after they both attacked and defended at range 1, closing for now.

**Closed by bitsai** 2019-07-08 05:26 UTC
Labels: Cannot reproduce
