### ISSUE TITLE
Fail to Save Player 1 List

### ISSUE THREAD

**Issue by neadcb** [Sandrem/FlyCasual#2179] opened 2019-08-14 02:35 UTC
I have tried to create a game VS the AI.  I create a list (Grevious/Soulles One; Sear / Kraken; 5x Trade Federation Drones), create or load an AI list and then when I launch the game I get an error that it failed to save my list and I am left with no list vs the AI list.  What is the best way to capture data / code to report here?

**Comment by neadcb** [comment] 2019-08-14 02:36
Note - when I start a new game, my list is saved but I get an error if I try to load it.
![image](https://user-images.githubusercontent.com/10949555/62990671-6d108a00-be12-11e9-9a34-aaaf977200a1.png)

**Comment by bitsai** [comment] 2019-08-14 02:54
The problem is due to Kraken (see https://github.com/Sandrem/FlyCasual/issues/2172) ; there was an issue with Tactical Relays in the 0.9.3 release.  It's fixed in the development branch and the fix will be included in the next release.

**Closed by bitsai** 2019-08-14 02:54 UTC

**Comment by neadcb** [comment] 2019-08-14 02:57
Excellent.  Thanks.


-----Original Message-----
