### ISSUE TITLE
TIE/VN SILENCER doesen't work

### ISSUE THREAD

**Issue by ObiWanNihilus** [Sandrem/FlyCasual#2729] opened 2020-06-07 12:13 UTC
![Bug X-Wing](https://user-images.githubusercontent.com/66556313/83968370-0b516d00-a8c9-11ea-8f01-f407a91e11d1.jpg)

**Comment by Sandrem** [comment] 2020-06-07 12:27
Bug is caused by AI-controlled TIE/BA.

Fixed in dev-branch.

**Closed by Sandrem** 2020-06-07 12:27 UTC
