### ISSUE TITLE
Lists won't generate

### ISSUE THREAD

**Issue by corranhorn25** [Sandrem/FlyCasual#277] opened 2017-10-14 02:43 UTC
<img width="1392" alt="screen shot 2017-10-13 at 9 38 07 pm" src="https://user-images.githubusercontent.com/32785660/31571820-830c412c-b05f-11e7-9122-9811449f1898.png">
on mac, tried generating that list several times, even with restart. Always renders with one ship on board only.

**Comment by Sandrem** [comment] 2017-10-14 13:28
Got this bug once on Windows too (not all ships where present after start of battle)

**Comment by corranhorn25** [comment] 2017-10-14 15:58
Love this game though. Been fun playing it so no worries. Keep at it.

**Comment by Sandrem** [comment] 2017-11-02 16:46
Cannot reproduce anymore, seems that bug is fixed with another related bugs.

**Closed by Sandrem** 2017-11-02 16:46 UTC
Labels: bug
