### ISSUE TITLE
Buzz droids attached to the rear guides of a medium base ship apparently are overlapped by the ship after executing a maneuver

### ISSUE THREAD

**Issue by boredompwndu** [Sandrem/FlyCasual#2737] opened 2020-06-09 01:41 UTC
[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4749374/LastReplay.zip)

**Comment by Sandrem** [comment] 2020-06-27 00:21
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2725

**Closed by Sandrem** 2020-06-27 00:21 UTC
Labels: Bug
