### ISSUE TITLE
Wolffe rear arc crash

### ISSUE THREAD

**Issue by Cannibal-Soup** [Sandrem/FlyCasual#2884] opened 2020-08-25 15:32 UTC
Crashed game with a rear-arc shot from Wolffe. I had just clicked 'always' when prompted on when to use his ability. 

Keep up the great work! Best mobile game on my phone! Will donate once I can afford it!

![Screenshot_20200825-082839_Fly Casual](https://user-images.githubusercontent.com/68479348/91194987-7b43e800-e6ad-11ea-98e1-410223c03892.jpg)

**Comment by rune-b** [comment] 2020-08-29 19:08
Thanks for reporting, and the kind words :)

This error is caused by Treacherous and has already been reported, so I will close this one.

Duplicate of #2832

**Closed by rune-b** 2020-08-29 19:08 UTC
Labels: Duplicate
