### ISSUE TITLE
Swarm Build Bugs

### ISSUE THREAD

**Issue by Vazkman** [Sandrem/FlyCasual#514] opened 2018-01-21 22:09 UTC
Hey there! 

I started testing the new features of 0.4.0 and found some bugs...

First image: I've built my squadron, no problems so far; when I started to build the AI squadron with 8 TIE Fighters, the game crashed when the 8th TIE was added, had to Alt + F4 out of the game.

Then I reopened it and tried to reproduce it a little bit different: 8 TIE's for me, 8 Z-95's for the AI. No errors so far, but some cards were invisible (image 2) and after hitting the start match button the game crashed (image 3).

Then, I tried to reproduce the error changing the colors of all TIE Fighters and Z-95's from both squadrons and the result was images 4 and 5.

![swarm bug 1](https://user-images.githubusercontent.com/1640572/35199095-126fec96-fee0-11e7-9af9-47203fa649f4.PNG)
![swarm bug 2](https://user-images.githubusercontent.com/1640572/35199096-1296328e-fee0-11e7-85af-bd640fbd5d40.PNG)
![swarm bug 3](https://user-images.githubusercontent.com/1640572/35199097-12bc0ff4-fee0-11e7-980c-592205817605.PNG)
![swarm bug 4](https://user-images.githubusercontent.com/1640572/35199545-b1c8b682-fee6-11e7-9d6f-91dc2a9088ea.PNG)
![swarm bug 5](https://user-images.githubusercontent.com/1640572/35199530-5e887804-fee6-11e7-9035-b8fd42ed7622.PNG)

[Crash_2018-01-21_132002.log](https://github.com/Sandrem/FlyCasual/files/1650274/Crash_2018-01-21_132002.log)
[Crash_2018-01-21_195050.log](https://github.com/Sandrem/FlyCasual/files/1650275/Crash_2018-01-21_195050.log)

**Comment by Sandrem** [comment] 2018-01-21 22:55
Thank you, this information is very useful.

**Comment by rats3g** [comment] 2018-02-09 21:30
Attempted to replicate the issue. I was able to create a squad of 8 TIE fighters with unique colors for each and a squad of 8 Z-95 with unique colors. I was also able to start the game with all 16 ships. 

Not sure if this was resolved by prior work or if its some sort of resource (memory?) issue. Unfortunately, I am unable to reproduce.

**Comment by Sandrem** [comment] 2018-02-20 19:47
Memory leaks in squad builder are fixed in development branch.

**Closed by Sandrem** 2018-02-20 19:47 UTC
Labels: Bug
