### ISSUE TITLE
Selflessness is redirecting crits as well as hits.

### ISSUE THREAD

**Issue by Kelbesq** [Sandrem/FlyCasual#768] opened 2018-04-06 04:52 UTC
I've this come up several times, both when used by a player, and when used by the AI.   One or more uncancelled crits get applied to the ship with the Selflessness card, and not the original target.

**Comment by Kelbesq** [comment] 2018-04-06 16:01
I was observing this in the 0.4.3 test release.   I will retest it in the official 0.4.3 release.

**Comment by Sandrem** [comment] 2018-04-06 16:03
I didn't fix anything in this part of code between "0.4.3 test" and "0.4.3 release".
Please, if you can reproduce problem - provide screenshot. At least, I will have information what squads were used.

**Comment by Kelbesq** [comment] 2018-04-06 16:06
I know I have seen it happen with Lowhhrick as Selflessness carrier. Is there a preferred squad I should use to reproduce the problem?

**Comment by Sandrem** [comment] 2018-04-06 16:09
No ideas about squad.

Some useful information for testing:
You can change dice results in debug console.
1) press "CTRL"+"~"
2) enter "help dice" to see how command is used
3) to see ID of ships - hold ALT
4) use console commands to add critical hit die / change another die to crit face

This can save you time =)

**Comment by Sandrem** [comment] 2018-04-07 14:16
I cannot reproduce this problem. Regualr hits were assigned to Selflessness host, crits were assigned to original defender.

**Comment by Kelbesq** [comment] 2018-04-07 15:54
I was unable to reproduce it either with a very basic squad.   Maybe there is some interaction I missed before, or I hit some corner case.    I will keep my eye out and document it if I see it again.

**Comment by Sandrem** [comment] 2018-04-07 16:08
OK. I will close this issue.
If you will get this problem again - inform me and provide screenshot of the battle and screenshot of console's last text (open by "CTRL+~").

**Closed by Sandrem** 2018-04-07 16:08 UTC
Labels: Cannot reproduce
