### ISSUE TITLE
Crash during rock placement 

### ISSUE THREAD

**Issue by barfolomew4** [Sandrem/FlyCasual#2816] opened 2020-07-13 03:59 UTC
My game crashed with igb igc and dengar and gas clouds. After placing the last rock I restarted and the crash happened again prior to placing forces in the next game. The opponent list was 4 skull with fearless and rocks. 

![Screenshot_20200712-235604_Fly Casual](https://user-images.githubusercontent.com/50247192/87269597-a24aaf80-c49b-11ea-803c-f9baee22ba41.jpg)

Find list below

{"name":"IGB IGC Dengar","description":"","faction":"scumandvillainy","points":200,"version":"2.4.11","pilots":[{"id":"ig88c","ship":"aggressorassaultfighter","points":69,"upgrades":{"cannon":["autoblasters"],"talent":["marksmanship"],"title":["ig2000"]}},{"id":"ig88b","ship":"aggressorassaultfighter","points":68,"upgrades":{"cannon":["autoblasters"],"talent":["marksmanship"],"title":["ig2000"]}},{"id":"dengar","ship":"jumpmaster5000","points":63,"upgrades":{"cannon":["autoblasters"],"crew":["ig88d"],"gunner":["greedo"],"illicit":["contrabandcybernetics"],"talent":["marksmanship"]}}],"vendor":{"lbn":{"builder":"Launch Bay Next","builder_url":"https://launch-bay-next.herokuapp.com","link":"https://launch-bay-next.herokuapp.com/print?lbx='IGB%20IGC%20Dengar'.200.3.0.(21.199.(3.578).(1.239).(15.374)).(21.198.(3.578).(1.239).(15.374)).(45.214.(3.578).(8.357).(16.367).(13.287).(1.239))"}}}

**Comment by Sandrem** [comment] 2020-07-13 22:22
Please, don't use gas clouds until release of new version.

Duplicate of https://github.com/Sandrem/FlyCasual/issues/2811

**Closed by Sandrem** 2020-07-13 22:22 UTC
