### ISSUE TITLE
Oddball ARC-170 pilot can be added, but not flown

### ISSUE THREAD

**Issue by SleepyJedi** [Sandrem/FlyCasual#1754] opened 2019-04-04 18:32 UTC
The Oddball ARC-170 pilot is visible in squad building, and can even be selected, but once the match starts, an error appears saying that "An error occurred during the creation of squadron" and none of the ships appear. This only happens with the ARC-170 version and not the V-19 Torrent pilot

**Comment by bitsai** [comment] 2019-04-04 19:27
Well spotted!  Good news is that this has already been reported (https://github.com/Sandrem/FlyCasual/issues/1704), and a fix is on the way!

**Comment by rune-b** [comment] 2019-04-04 20:10
Closing this one since it is a duplicate of #1704

**Closed by rune-b** 2019-04-04 20:10 UTC
Labels: Duplicate
