### ISSUE TITLE
Crash after Fifth Brother/Homing Missile

### ISSUE THREAD

**Issue by sthej** [Sandrem/FlyCasual#2770] opened 2020-06-24 04:23 UTC
![error](https://user-images.githubusercontent.com/47505730/85500071-0adef480-b5a0-11ea-87a1-9c471cf002ca.png)
[Replays - Copy.zip](https://github.com/Sandrem/FlyCasual/files/4823183/Replays.-.Copy.zip)

**Comment by Sandrem** [comment] 2020-06-24 04:30
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2668

**Closed by Sandrem** 2020-06-24 04:30 UTC
