### ISSUE TITLE
Seventh sister on decimator

### ISSUE THREAD

**Issue by drummkid** [Sandrem/FlyCasual#2080] opened 2019-07-15 01:02 UTC
As a crew, seventh sister has her force canceled every time an enemy ship performs a stress maneuver in range 0-1 of the ship shes on, no ability to tractor or jam (it just outright cancels the force)

**Comment by Xan7o** [comment] 2019-07-15 06:07
I look to it and it goes to auto JAM
Ships perform a red manouver, Sister spends force, ship loses stress so perform focus action and losses it because sisters give auto jam.

Only way when I can give someone tractor token is when a ship at range 1 will be dealt a 2-stress critical dmg.

**Comment by bitsai** [comment] 2019-07-15 08:43
Did some testing in the current development branch, playing both as and against a Decimator carrying Seventh Sister crew.

When playing the Decimator, Seventh Sister gave me the choice between Jam & Tractor tokens as expected.  NOTE: as @Xan7o mentioned, when Jamming, if the target ship performs an action to gain a green token or target lock, both the Jam and green/lock tokens will go away, which can make it seem like Seventh Sister's Force was spent for nothing.

When playing against an AI Decimator, I did find an issue where I was given the choice for what the AI Seventh Sister ability should do.  I've opened a small pull request to fix this.

@drummkid if you're still seeing Seventh Sister crew seemingly do nothing (either on your squad or the AI squad), please take a screenshot and provide steps on how to reproduce the situation.  Thanks!

**Comment by drummkid** [comment] 2019-07-15 10:34
Here's what I see:

Card reads "when an enemy ship at range 0-1 would gain a stress token, you
*may* spend one force to have it gain one tractor or one jam token
instead". The card gives player choice if ability even fires in the first
place, and if it does player gets to choose how it happens.

Run seventh sister on a ship (decimator or lambda) and have enemy ship
perform a red maneuver on their turn. If the maneuver finishes in range 0-1
of your ship, you're not given 'choice'. Ability auto fires with jam token,
which isn't what the card states. Burns the force and auto fires the
ability, which also takes away utility of 7th sister.

**Comment by bitsai** [comment] 2019-07-15 10:42
Right; as I mentioned in my edited comment above, I tracked this down to the choice mistakenly being given to the wrong player.  The fix will be part of the next release.

**Closed** 2019-07-15 13:17 UTC
Labels: Bug
