### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by louislouisl** [Sandrem/FlyCasual#3130] opened 2021-02-05 02:12 UTC
Loaded a autosace squad (previous version) against a random squad, crashed as soon as the game loaded.

![Screenshot_20210205-020807](https://user-images.githubusercontent.com/8874821/106979988-4e652800-6757-11eb-9f57-1d06956a6289.png)

**Comment by louislouisl** [comment] 2021-02-05 02:13
[log.zip](https://github.com/Sandrem/FlyCasual/files/5929662/log.zip)

**Comment by stormwalker628** [comment] 2021-02-05 03:15
![2021-02-04 19_11_54-Fly Casual](https://user-images.githubusercontent.com/78578095/106984917-51432700-671d-11eb-8d4c-3886137c52ba.jpg)

I'm having the same issue.  It looks to be something related to Avatars.

**Comment by Sandrem** [comment] 2021-02-05 03:21
Try to change avatar in Options. Maybe this is caused by some specific avatars.

**Comment by stormwalker628** [comment] 2021-02-05 03:37
> 
> 
> Try to change avatar in Options. Maybe this is caused by some specific avatars.

I get the error just going to the Options area.  After hitting close there are no avatars available.  This isn't crashing the game for me, but Avatars aren't showing up in the game either.

If it helps, this is a clean install.  I deleted all old files before updating.

**Comment by Sandrem** [comment] 2021-02-05 03:40
Do you remember what avatar you used in previous version?

**Comment by stormwalker628** [comment] 2021-02-05 03:41
> 
> 
> Do you remember what avatar you used in previous version?


i think I was using Han Solo.

**Comment by AlgernonFTW** [comment] 2021-02-05 05:25
I'm getting all kinds of errors as well, upon game startup and even in menus.

**Comment by louislouisl** [comment] 2021-02-05 09:21
> Do you remember what avatar you used in previous version?

My avatar was the jawa technician I think. Either that or default

**Comment by philippebureau** [comment] 2021-02-05 14:29
same error.  I think I used Dengar avatar.

in the avatar menu, I do not have any options to pick another one

![avatar](https://user-images.githubusercontent.com/8918617/107046419-99516080-6794-11eb-91f7-d69d7a8bc30d.jpg)

**Comment by philippebureau** [comment] 2021-02-05 14:43
I deleted folders in C:\Users\<user>\AppData\LocalLow\Sandrem\

restarted the game and get same error.

the new files created does indeed try to load dengar avatar I guess

![avatar2](https://user-images.githubusercontent.com/8918617/107048156-9b1c2380-6796-11eb-879c-fbeb125c0466.jpg)

I still have no avatar selection option

**Comment by Sandrem** [comment] 2021-02-05 17:09
Try this workaround for Windows:
Open "regedit"
Navigate to "HKEY_CURRENT_USER\SOFTWARE\Sandrem\Fly Casual"
Delete entry "Avatar_<something>".

**Comment by philippebureau** [comment] 2021-02-05 17:15
WORKS !

awsome, Thank you

**Comment by Sandrem** [comment] 2021-02-13 05:41
Fixed, update will be released soon.

**Closed by Sandrem** 2021-02-13 05:41 UTC
