### ISSUE TITLE
Stealth device removed trigger will keep occuring

### ISSUE THREAD

**Issue by jurriaanr** [Sandrem/FlyCasual#940] opened 2018-05-19 19:57 UTC
After the first time a ship with SD is hit, it will be greyed out, and a message will pop up and 1 agility is lost. This is how it should work. However, everytime after it will again be triggered, allowing you to choose the SD trigger to execute, and will contnue to subtract agility.

![sd](https://user-images.githubusercontent.com/7426848/40272579-ca4fa244-5baf-11e8-8450-870792f58311.JPG)

**Comment by rune-b** [comment] 2018-05-20 06:56
Duplicate of #925  
Already fixed in development branch

**Closed** 2018-05-20 09:02 UTC
Labels: Bug
