### ISSUE TITLE
0.4.3.1 - System Crash when Restarting completed game

### ISSUE THREAD

**Issue by bcutlerGC** [Sandrem/FlyCasual#812] opened 2018-04-13 13:06 UTC
(Windows PC) This issue appears to be consistent and I have seen it in multiple games with different ships involved.

Player vs AI game
Complete the game (by winning as usual)
Select Restart from the menu
Loading page is displayed for a while then the system crashes

Crash log is generated (see attached)
Crash.dmp file was empty so is not included
[error.log](https://github.com/Sandrem/FlyCasual/files/1907432/error.log)

**Comment by Sandrem** [comment] 2018-04-29 02:16
Cannot reproduce, not enough information.
But some fixes are done.
Try to reproduce in 0.5.0, when this version will be released.

**Closed by Sandrem** 2018-04-29 02:16 UTC
