### ISSUE TITLE
Boba Fett Crew

### ISSUE THREAD

**Issue by tamebullgames** [Sandrem/FlyCasual#2109] opened 2019-07-19 02:31 UTC
Can't place a ship with Boba Fett crew without massive errors.

**Comment by Sandrem** [comment] 2019-07-19 03:47
Screenshots? What OS do you use?

**Comment by Sandrem** [comment] 2019-07-19 03:49
Nevermind, I found duplicate of this issue with required details.
Please, provide more details next time when you report a bug.

Closed as duplicate of https://github.com/Sandrem/FlyCasual/issues/1723

**Closed by Sandrem** 2019-07-19 03:49 UTC
