### ISSUE TITLE
Zeb upgrade on Hera, unable to attack range 0 fang fighter

### ISSUE THREAD

**Issue by Zipline20** [Sandrem/FlyCasual#1519] opened 2019-02-08 03:48 UTC
![image](https://user-images.githubusercontent.com/27784255/52457943-a7bf0000-2b19-11e9-811a-e7fb80e517de.png)

**Comment by Zipline20** [comment] 2019-02-08 03:52
However in this instance, I am able to make a range 0 attack with Zeb. 
![image](https://user-images.githubusercontent.com/27784255/52458034-30d63700-2b1a-11e9-9579-5e7d57582486.png)

I had to pop collision detector to be able to shoot on the asteroid.

**Comment by krumok** [comment] 2019-03-08 22:31
Same issue, i have Zeb on Hera and cannot attack at range 0 with Hera versus t65
![Screenshot_2019-03-08-22-57-36-475_com sandrem flycasual](https://user-images.githubusercontent.com/12997440/54059599-01d6e200-41fa-11e9-808d-18d7646dd6ce.png)

But the t65 can shoot to Hera at range 0
![Screenshot_2019-03-08-22-58-38-539_com sandrem flycasual](https://user-images.githubusercontent.com/12997440/54059630-1adf9300-41fa-11e9-99c0-33d8e1410546.png)

**Comment by bitsai** [comment] 2019-07-08 23:18
Re-tested this in latest development branch using Hera vs. Norra (both with Zeb crew + Intimidation) in a hotseat game, flew them into each other at an angle and was not able to reproduce the error (both were able to shoot each other w/ out issues), closing for now.

**Closed by bitsai** 2019-07-08 23:18 UTC
Labels: Cannot reproduce
