### ISSUE TITLE
Cannot start and save a game with a separatist droid swarm

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2205] opened 2019-08-20 07:51 UTC
I tried making this squad:

Captain Sear + TA-175 + Soulless one
Precise Hunter
Separatist Drone x6

I got this error:

_An error occured during the creation of squadron "Autosave (player 1).json"_

And then the game started with only the enemy squad, not the one I tried to create.

**Comment by bitsai** [comment] 2019-08-20 08:02
Duplicate of #2172, fix will be included in the next release.

**Closed by bitsai** 2019-08-20 08:02 UTC
