### ISSUE TITLE
Dutch Vander AI assigns Target Locks before movement phase.

### ISSUE THREAD

**Issue by Liquidlogic1** [Sandrem/FlyCasual#179] opened 2017-08-29 00:32 UTC
The Dutch Vander AI will attempt to hand out a Target lock to a friendly ship before it completes it's movement phase.  This can result in Dutch performing red maneuvers and still handing out TL's.

**Comment by Sandrem** [comment] 2017-08-29 00:41
HotAC AI aquires Target Lock before movement (image attached)
![hotac ai example](https://user-images.githubusercontent.com/6347443/29799302-7808d87a-8c6b-11e7-984d-87a35dd39f7c.jpg)

So, target lock is aquired (and ability is triggered and resolved) even if Dutch Vander skips his normal action phase due to red maneuver/collision/asteroid.

If his behavior is according to description and doesn't cause any additional problems (game is not hanged up, phases of game works in correct order...) - comment here, I will close this issue as not a bug,

**Comment by Liquidlogic1** [comment] 2017-08-29 01:48
Ah yes. That makes sense. So according the the HotAC AI he could use his pilot ability then. You can close it.

**Closed** 2017-08-29 01:49 UTC
Labels: bug
