### ISSUE TITLE
Console fire does not trigger if ship has no enemies in arc to attack

### ISSUE THREAD

**Issue by ootinni** [Sandrem/FlyCasual#2115] opened 2019-07-21 20:14 UTC

**Comment by bitsai** [comment] 2019-07-22 03:34
Tried to reproduce the issue but didn't succeed.  In my test games, when my ship has Console Fire, it triggered even when there were no enemies in range or in arc.

@ootinni I'm going to optimistically close this for now, but if you see this again, please feel free to re-open (and if you can, provide screenshots, steps to help us reproduce, and any other details you can).  Thank you!

**Closed by bitsai** 2019-07-22 03:34 UTC
Labels: Cannot reproduce

**Comment by ootinni** [comment] 2019-07-22 06:08
In my situation it was Vader cheerfully getting away without console fire triggering twice when pointing away. Maybe it was because he was shooting first (no other I6 on table)..

Will keep an eye out for it again.

Is there a way to keep the logs saved somewhere?

**Comment by bitsai** [comment] 2019-07-22 07:22
Certainly!  The location of the replay logs depends on your operating system:

- Mac: `~/Library/Application Support/unity.Sandrem.X-Wing TMG Simulator/Second Edition/Replays`
- Windows: `%userprofile%\AppData\LocalLow\Sandrem\Fly Casual_ X-Wing TMG Simulator\Second Edition\Replays\`

One possibility is that since Vader can spend Force to take multiple actions in a round, perhaps he took an extra action at some point to fix the Console Fire crit?  If you see this again, hovering the cursor over the crit tokens will show exactly what crits a ship currently has.

**Comment by ootinni** [comment] 2019-07-22 10:59
Is it possible to get the logs in Android?

Definitely wasn't repaired, cos Vader blew up from the console fire a couple turns later..

I'll see if I can find the logs, if not will keep an eye out for it happening again.. though will have to rely a series of unlikely occurences for it to naturally come up!

Thanks for looking into it

**Comment by ootinni** [comment] 2019-07-22 11:01
OK found it in Android, but it's only the last game logged :(

For now I guess we leave this issue to the wind...
