### ISSUE TITLE
Predator not working as intended

### ISSUE THREAD

**Issue by iantheace** [Sandrem/FlyCasual#754] opened 2018-03-27 19:51 UTC
Currently predator is not taking the enemy pilot skill into account, in a game vs 2 PS3 enemies I was able to reroll 2 attack dice, this should only be the case against PS2 and below.

**Comment by Sandrem** [comment] 2018-03-31 20:30
Cannot reproduce:
![image](https://user-images.githubusercontent.com/6347443/38167269-363e1558-353b-11e8-8ee2-007a95128447.jpg)

Please, next time provide screenshot, where I can see that target of attack has PS 3 or higher and 2 dice are selected in reroll window of Predator's ability.

Please, try to reproduce this bug. Maybe, some additional requirements are needed (for example, Adaptivity (-1) is installed, or this was a network game)/

**Comment by Sandrem** [comment] 2018-03-31 20:35
Also, code of this part is simple, so I doubt that bug is real

NumberOfDiceCanBeRerolled = (Combat.Defender.PilotSkill > 2) ? 1 : 2,
(syntax: (check condition) ? what value if true : what value if false)

I will close this issue soon if no one can reproduce this problem.

**Comment by iantheace** [comment] 2018-03-31 21:38
Sorry I can't recreate this either, I'm not sure what I was doing to cause this really sorry!

**Comment by Sandrem** [comment] 2018-03-31 21:40
Maybe you just misclicked and selected Target Lock dice modification instead.
I close this issue.

Please, next time take a screenshot if you encounter some error - this will help me a lot to understand possible reasons.

**Closed by Sandrem** 2018-03-31 21:40 UTC
Labels: Cannot reproduce
