### ISSUE TITLE
Zeb Orellios Range 0 attack not working

### ISSUE THREAD

**Issue by hellowrld136** [Sandrem/FlyCasual#3173] opened 2021-02-19 04:06 UTC
Zeb Orellios is not allowing this Ghost to attack at range 0, and conversely, isn't letting enemy ships shoot the Ghost at range 0.
![Screen Shot 2021-02-18 at 8 52 17 PM](https://user-images.githubusercontent.com/70863305/108455768-12889300-722c-11eb-9cf8-7b7c491008bd.png)
![Screen Shot 2021-02-18 at 9 05 13 PM](https://user-images.githubusercontent.com/70863305/108456229-1bc62f80-722d-11eb-9645-e9376fd9eb23.png)

**Comment by ClarenceR89** [comment] 2021-03-12 08:01
Same issues as #3109

Zeb Crew does not allow range 0 attacks

**Comment by Sandrem** [comment] 2021-05-08 14:01
Duplicate of https://github.com/Sandrem/FlyCasual/issues/3109

**Closed by Sandrem** 2021-05-08 14:01 UTC
