### ISSUE TITLE
N-1 Starfighter - Anakin pilot skill

### ISSUE THREAD

**Issue by Perribrus** [Sandrem/FlyCasual#2586] opened 2020-04-02 20:04 UTC
I tried to use N-1 Starfighter Anakin Skywalker pilotskill (the barrel roll before revealing dial), but it was obstructed by friendly ship.
![bugscreen_2020-04-02 kl  21 53 51](https://user-images.githubusercontent.com/63073617/78296192-927f0f00-752d-11ea-8bcb-6f38aa8d907b.png)
![bugscreen2_2020-04-02 kl  21 54 41](https://user-images.githubusercontent.com/63073617/78296198-9448d280-752d-11ea-995f-557b2877a26b.png)

**Comment by rune-b** [comment] 2020-04-04 21:45
Thanks. This has already been reported, so I'm closing this one

duplicate of #2447

**Closed by rune-b** 2020-04-04 21:45 UTC
