### ISSUE TITLE
"Deathfire" performing death-triggered attack causes crash

### ISSUE THREAD

**Issue by Rczech42** [Sandrem/FlyCasual#2872] opened 2020-08-15 04:38 UTC
When Deathfire is destroyed the game prompts you to choose between performing an attack or dropping a device.  I selected perform attack.  I cannot recall if I threw dice or not but the game has crashed several times during this moment Deathfire dies.

![Deathfire crash](https://user-images.githubusercontent.com/10158767/90305341-675ee180-de76-11ea-8746-cc3b2cde4fa2.jpg)

[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/5078101/LastReplay.zip)

**Comment by Arahain** [comment] 2020-08-17 14:29
Hi, I am currently tracking this bug and it looks like the problem occured when Admiral Sloane tried to assign Stress to the attacker that killed Deathfire but the attacker was already killed by deathfire at that time. I'll update as soon as I have a fix ready.

**Comment by Arahain** [comment] 2020-08-17 14:41
I was able to reproduce the bug without destroying the attacker, it appears right after the deathfire triggered attack (after rolling dice), before Sloane was able to assign the  stress. The issue does not occur if I pair Admiral Sloane with a normal Tie though.

**Comment by Sandrem** [comment] 2020-08-18 20:57
Fixed by Arahain

**Closed by Sandrem** 2020-08-18 20:57 UTC
