### ISSUE TITLE
Crash on TLT target destroyed.  

### ISSUE THREAD

**Issue by Alpha-17** [Sandrem/FlyCasual#837] opened 2018-04-20 21:57 UTC
Ship with one hull left was hit by TLT first hit and destroyed.  Game tried to roll second TLT shot, and froze.  
![31036815_1876033309083071_5549278886677708800_n](https://user-images.githubusercontent.com/38572727/39075535-dac6b6c2-44bb-11e8-9c26-274fe5c1fb96.jpg)

**Comment by Sandrem** [comment] 2018-05-08 19:30
Cannot reproduce.
Another related bugs are fixed by rune-b.

Inform us if you will see this error again in next update.

**Closed by Sandrem** 2018-05-08 19:30 UTC
