### ISSUE TITLE
Grand Inquisitor crew not treating action as red

### ISSUE THREAD

**Issue by drail14me** [Sandrem/FlyCasual#2067] opened 2019-07-14 00:14 UTC
When the AI uses Grand Inquisitor crew's ability, it does not treat the action as Red and sometimes takes multiple actions.

When using Grand Inquisitor Crew as a player, it only allows a red Focus action and not other white actions on the action bar.

I had both happen while using Grand Inquisitor on a VT-49 as both player and with AI

**Comment by bitsai** [comment] 2019-07-14 13:07
I played a test game vs AI, pitting 2 Patrol Leaders w/ Grand Inquisitor crew against each other.  I was not able to reproduce the AI taking multiple actions w/ the crew, or the player not seeing the right set of actions (see screenshot, which correctly offered me 3 options when the enemy moved after I already took a Focus action).

I did see the AI not treating the action as Red and will look into it.  In the meantime, could you try to reproduce the other two problems and share the steps needed to do so?

<img width="1280" alt="Screen Shot 2019-07-14 at 5 55 51 AM" src="https://user-images.githubusercontent.com/260863/61184022-77feb180-a5fd-11e9-9741-b0f0a1d45461.png">

**Comment by Sandrem** [comment] 2019-07-14 13:38
As I remember, in current version AI always treats red action as white, because it is hard to calculate correct priority of red action (when AI wants to gain stress token for an action, and when it is better to skip it). in most of cases it is used for red linked "Rotate arc" actions.
As a workaround, I propose just to skip all ability if ship is controlled by AI.

**Comment by bitsai** [comment] 2019-07-14 13:53
@Sandrem ah ok; I had just removed the code that lets AI treat red actions as white, but now I understand why that's there.  I'll restore that and simply disallow AI from using Grand Inquisitor crew's ability for now.

**Comment by drail14me** [comment] 2019-07-14 14:21
Sandrem is correct, in HotAC rules, AI treats red action as white. I’ve tested again and here’s what happened.

An I1 pilot at range 2 of Grand Inquisitor on VT-49 revealed it’s dial. Grand Inquisitors ability triggers and VT-49 took Reinforce action.
VT-49 then completed a white maneuver and took a Focus action. That’s how the VT-49 was getting multiple actions. 

Later in the game, the VT-49 activated and completed a white maneuver and took a reinforce action. Afterwards, an I4 pilot within range 2 revealed it’s dial and triggered Grand Inquisitor which gave the VT-49 a white focus.

Thanks for looking into this.

Dennis

**Comment by drail14me** [comment] 2019-07-14 14:33
Sandrem is correct, in HotAC rules, AI treats red action as white. I’ve tested again and here’s what happened.

An I1 pilot at range 2 of Grand Inquisitor on VT-49 revealed it’s dial. Grand Inquisitors ability triggers and VT-49 took Reinforce action.
VT-49 then completed a white maneuver and took a Focus action. That’s how the VT-49 was getting multiple actions. 

Later in the game, the VT-49 activated and completed a white maneuver and took a reinforce action. Afterwards, an I4 pilot within range 2 revealed it’s dial and triggered Grand Inquisitor which gave the VT-49 a white focus.

Thanks for looking into this.

Dennis

**Comment by bitsai** [comment] 2019-07-14 14:49
@drail14me thanks for digging up those additional details!  as per the suggestion from @Sandrem, I've disabled Grand Inquisitor crew's ability for the AI for now, so in the next release you should no longer see AI-related shenanigans with this upgrade.

Do you still see an incorrect list of options when using the upgrade as the player?

**Comment by drail14me** [comment] 2019-07-14 15:11
I’m not sure you need to disable the Grand Inquisitor. It just seems to be a product of the HotAC AI. Most of the time, the VT-49 gets blocked so it gets no action. This is the reason people put the GI on it so it can get an action before or after it gets blocked. I’m not sure there is an easy fix for this since AI treats all actions as white. 

I have not been able to recreate the other issue. It happened once where the only option was a red Focus. I don’t remember having any Critical damage at the time. 

Dennis

**Comment by bitsai** [comment] 2019-07-14 15:39
IMHO it makes sense to disable GI crew for the AI for now.  Most people understand that many cards are not supported by the FlyCasual AI yet.  Relatively fewer people have the context that the AI currently treats red actions as white.  Just for our own sanity, I would prefer leaving this disabled for now, to avoid repeated bug reports about AI not taking stress when using the GI crew upgrade :)

Besides the Damaged Sensor Array crit, the other situation I can think of where you might have only a red Focus available is if the ship was Ionized, not sure if that was the case you ran into though.

I'm gonna optimistically close this issue for now, but if you ever see the GI crew give an incorrect list of actions to choose from, please take a screenshot and re-open this issue.  Thanks!

**Closed by bitsai** 2019-07-14 15:39 UTC
Labels: Bug
