### ISSUE TITLE
Tel Trevura Respawn caused error

### ISSUE THREAD

**Issue by Amigoameise** [Sandrem/FlyCasual#2848] opened 2020-08-02 08:46 UTC
After Tel got Destroyed, at the next plannignPhase its not possible to  set him. Ive got always the message " Ship is overlapping" or an error message 
![Screenshot 02-08-2020 10 44 22](https://user-images.githubusercontent.com/26957887/89119286-62308880-d4ad-11ea-858d-f145a118ecca.png)

**Comment by rune-b** [comment] 2020-09-08 16:37
Thanks for reporting.

I assume this is a duplicate of #2824 which has already been fixed for the next release. So I'm closing this one.

Please let us know if this happens again after the next update.

**Closed by rune-b** 2020-09-08 16:37 UTC
