### ISSUE TITLE
Proximity Mines do not fire if tractored onto

### ISSUE THREAD

**Issue by wavemanns** [Sandrem/FlyCasual#1485] opened 2019-02-02 00:48 UTC
If the Prox mine token covers 2 ships, the system chooses automatically instead of prompting player and will kill a friendly ship if enemy is also covered. I think it is going by pilot skill right now and initiative if both are the same. Also, Proximity mines seem to be very iffy at the edges. They don't go off when ship is nicking the edge when dropped and they don't do off when you tractor someone on to them.

**Comment by bitsai** [comment] 2019-07-10 09:27
First issue is duplicate of #555, updating title accordingly.

**Comment by Sandrem** [comment] 2019-07-15 22:42
Fixed

**Closed by Sandrem** 2019-07-15 22:42 UTC
Labels: Bug
