### ISSUE TITLE
OS-1 Arsenal Loadout and error during creation of squadron

### ISSUE THREAD

**Issue by ScarryHiggy** [Sandrem/FlyCasual#1742] opened 2019-04-02 22:52 UTC
Update: Yeah, I just narrowed it down to Oddball. I missed that there was already an issue with his name reported and a fix being implemented

macOS 10.14.3

I just built this 5 ship squad and received  "An error occurred during the creation of squadron 'Autosave (Player 1).json'"
SS attached for squad reference. I will see if I can find the combination that causes the error.
<img width="1276" alt="Screen Shot 2019-04-02 at 6 46 04 PM" src="https://user-images.githubusercontent.com/49127443/55441324-64609b00-5578-11e9-8bcb-7d9fddac8a5d.png">

**Comment by bitsai** [comment] 2019-04-02 22:54
I think this is due to the "Odd Ball" naming issue discovered in https://github.com/Sandrem/FlyCasual/issues/1704, which will be fixed in the next release.

**Comment by ScarryHiggy** [comment] 2019-04-02 22:56
Yeah, I just narrowed it down to Oddball. I missed that there was already an issue with his name reported

**Comment by rune-b** [comment] 2019-04-02 23:10
Duplicate

**Comment by LanikTnt** [comment] 2019-07-16 19:10
I have the same issue 0.9.2 and its repeatable when I click Load.  No Odd Ball in list.
![Autosave_player1](https://user-images.githubusercontent.com/33493097/61322522-7981d280-a7d3-11e9-94ce-04c898258ceb.jpg)

**Comment by bitsai** [comment] 2019-07-16 19:19
@LanikTnt if you can, could you take a screenshot of the squad you saved that couldn't be loaded?

**Comment by LanikTnt** [comment] 2019-07-16 19:21
It's attached to my post with the 3 Nus and Jendon.  When I clock Load I get that error.

**Comment by bitsai** [comment] 2019-07-16 20:13
Oh, sorry! I misunderstood, thought you ran into this with a Republic list
of your own.

**Comment by LanikTnt** [comment] 2019-07-16 20:14
No worries.

**Comment by Sandrem** [comment] 2019-07-16 20:16
Seems that bug is caused by in-game order of installation of upgrades. When Diamond-Boron Missiles are tried to be installed - OS-1 Arsenal Loadlout is not installed yet, and there is no second missiles slot available.

**Comment by Sandrem** [comment] 2019-07-16 20:19
In "load from json" part of code, we need first to see what upgrades create new slots, install them first, and only then install other upgrades.

**Comment by RockoTDF** [comment] 2019-07-18 08:13
I'm having this same issue with Major Vynder and the OS-1 title, only it happens inconsistently.  When I first created/played the list (in this version) there was no problem.  Sometimes the list won't load in the menu, sometimes it does, only to get the autosave error once you're at the table.  But if you make it that far, you have nothing on your side of the screen/table.

**Comment by LanikTnt** [comment] 2019-07-18 14:47
@RockoTDF Are you using Diamond Boron missiles?  The devs figured out the order of their checks for slots and applying the upgrade is the problem.  I switched it to Concussion and it gets around the issue (though obviously I'm going to play Diamond Boron missiles in RL instead).

**Comment by RockoTDF** [comment] 2019-07-20 12:37
@LanikTnt Nope, using proton torps and barrage rockets.  The rockets must try and load before the title and not have the second missile slot they need.

**Comment by Sandrem** [comment] 2019-07-23 10:38
Fixed

**Closed by Sandrem** 2019-07-23 10:38 UTC
Labels: Bug
