### ISSUE TITLE
SLAM crashes an internet game

### ISSUE THREAD

**Issue by andrelpgoncalves** [Sandrem/FlyCasual#851] opened 2018-04-24 02:49 UTC
Hi,
We found a new issue for you.
I tried a couple times to use SLAM (with Miranda) in Internet Game and it crashes the battle.

**Comment by Sandrem** [comment] 2018-04-29 06:07
Duplicate of https://github.com/Sandrem/FlyCasual/issues/846

**Closed by Sandrem** 2018-04-29 06:07 UTC
Labels: Bug, Critical
